### ISSUE TITLE
Possible crash

### ISSUE THREAD

**Issue by yorik100** [calamity-inc/Stand-Feedback#100]
- **Obvious problem description**
  - Console causing crashes (?)
- **Steps to reproduce**
  - Spam console a lot for a very long time
  - After a while, CMD will crash
- **Possible fix**
  - Auto clear console if it's way too full

**Comment by alessandromrc** [comment]
> * **Obvious problem description**
>   
>   * Console causing crashes (?)
> * **Steps to reproduce**
>   
>   * Spam console a lot for a very long time
>   * After a while, CMD will crash
> * **Possible fix**
>   
>   * Auto clear console if it's way too full

Do you have any way to reproduce this...?
Not sure if you are spamming on purpose from within lua scripts or what...

**Comment by Sainan** [comment]
This would be a Microsoft issue, but I doubt it's actually.

**Comment by yorik100** [comment]
> > * **Obvious problem description**
> >   
> >   * Console causing crashes (?)
> > * **Steps to reproduce**
> >   
> >   * Spam console a lot for a very long time
> >   * After a while, CMD will crash
> > * **Possible fix**
> >   
> >   * Auto clear console if it's way too full
> 
> Do you have any way to reproduce this...? Not sure if you are spamming on purpose from within lua scripts or what...

Summon monkeys in many people's cars using Dolos to spam false flags in console and stay connected for like 6 hours

**Comment by Sainan** [comment]
The "false flags" you are seeing are your game client being broken and needing a restart. This is likely an issue with the Lua scripts you are using.

**Comment by yorik100** [comment]
> The "false flags" you are seeing are your game client being broken and needing a restart. This is likely an issue with the Lua scripts you are using.

Modded Event T6 is from Lua? A friend of mine did the test, he also gets spammed without loading anything when I summon chimps in other people's cars, they're updating a spawned entity.
![image](https://github.com/calamity-inc/Stand-Feedback/assets/16320315/cb41268b-29c5-43ef-b98a-c245e1b5ec0e)
![image](https://github.com/calamity-inc/Stand-Feedback/assets/16320315/247dd600-3bc4-49f7-a526-5185b021dd22)
![image](https://github.com/calamity-inc/Stand-Feedback/assets/16320315/24807853-3005-4849-9c25-1c26c3c28033)

**Comment by alessandromrc** [comment]
> > The "false flags" you are seeing are your game client being broken and needing a restart. This is likely an issue with the Lua scripts you are using.
> 
> Modded Event T6 is from Lua? A friend of mine did the test, he also gets spammed without loading anything when I summon chimps in other people's cars, they're updating a spawned entity.

They didn't mention any lua related issue to that T6 Modded Event...

**Comment by yorik100** [comment]
> This would be a Microsoft issue, but I doubt it's actually.

Nevermind, it's not an issue, CMD is actually clearing itself overtime

**Comment by alessandromrc** [comment]
> > This would be a Microsoft issue, but I doubt it's actually.
> 
> 
> 
> Nevermind, it's not an issue, CMD is actually clearing itself overtime

Also, wasn't able to reproduce this at all... Left the game open in public sessions with every possible logging feature enabled for hours and literally nothing happened.
