### ISSUE TITLE
False Kick Event (S3) and False Unusual Events

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#101]
This is one of my friends and he isn't modding, i've also gotten that from other persons earlier today.
![Kick Event 1](https://github.com/calamity-inc/Stand-Feedback/assets/135753695/1345f5cc-90eb-4a20-8125-92257147ebe5)
![Kick Event 2](https://github.com/calamity-inc/Stand-Feedback/assets/135753695/9a08336a-33df-41a8-98fb-a91f5655dc9a)

Also had Unusual events that are most likely false positives as I had a lot since GTA updated.
![Unusual Events](https://github.com/calamity-inc/Stand-Feedback/assets/135753695/97bcebb4-7614-473c-ba00-bcdebff0cfcc)

**Comment by isytrana** [comment]
Just noticed that the False Kick Event will be fixed, I'm leaving it open for the false unusual events.

**Comment by alessandromrc** [comment]
It's actually always the same Script Event ngl...
