### ISSUE TITLE
Blocked from joining Karma Incorrectly kicking regular players even if you have joined normally for a while

### ISSUE THREAD

**Issue by latiao-1337** [calamity-inc/Stand-Feedback#106]
- **Obvious problem description**
I had been playing normally in the lobby for more than 30 minutes, but suddenly Block Join Karma kicked out 2 players by mistake

- **Steps to reproduce**
N/A
- **Sufficient context**
![图片](https://github.com/calamity-inc/Stand-Feedback/assets/146958060/c48fc6f0-413c-40b1-ae55-fe5924bab7b8)

**Comment by Sainan** [comment]
This is not a mistake. It is possible for players to block your joins of interiors etc.

**Comment by latiao-1337** [comment]
Thanks for your reply, but I think he may not be a cheating player. I was playing the free mode ceo mission with him. This may be a false detection
