### ISSUE TITLE
Memory became unwritable in Stand 116.4

### ISSUE THREAD

**Issue by Polyester-ak-Parci** [calamity-inc/Stand-Feedback#107]
- **Obvious problem description**
  - In Stand 116.4 some memory(with executable code) that was possible to write in previous become unwritable

**Comment by Sainan** [comment]
This is intentional. Could you provide an example where you would need to write over code?

**Comment by Polyester-ak-Parci** [comment]
> This is intentional. Could you provide an example where you would need to write over code?

That's not the only place but for example here 
48 8B C4 48 89 58 20 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 B0 48 81 EC 50 01 00 00 4C

**Comment by Sainan** [comment]
Could you be more specific? Why are you trying to overwrite bytecode?

**Comment by Polyester-ak-Parci** [comment]
Also please explain the reason if possible

**Comment by Polyester-ak-Parci** [comment]
> Could you be more specific? Why are you trying to overwrite bytecode?

I just want to set my hooks where it is necessary for me.

**Comment by Sainan** [comment]
Hooking into game functions is not a feature of the Lua API.

**Comment by Sainan** [comment]
> Also please explain the reason if possible

This is done for security as there are tons of risks with unmanaged access to bytecode. I have also not seen any use-cases of this, so it seemed like a no-brainer risk mitigation.

**Comment by Polyester-ak-Parci** [comment]
> > Also please explain the reason if possible
> 
> This is done for security as there are tons of risks with unmanaged access to bytecode. I have also not seen any use-cases of this, so it seemed like a no-brainer risk mitigation.

Can you please return the ability to write to any place in memory? let it be enabled by a separate check mark or available in the lua developer mode

**Comment by Polyester-ak-Parci** [comment]
Like internet connection

**Comment by Sainan** [comment]
I have yet to see any valid use case of this, and I highly doubt a user could possibly understand the implications of any such checkbox.

**Comment by Polyester-ak-Parci** [comment]
> I have yet to see any valid use case of this, and I highly doubt a user could possibly understand the implications of any such checkbox.

You can hide this feature somewhere in the settings and not allow it to be switched via the lua api.

**Comment by Sainan** [comment]
Maybe explain what your reason for needing this is.

**Comment by Polyester-ak-Parci** [comment]
> Maybe explain what your reason for needing this is.

to set hooks in places where I need it. or for example, here is the code to disable collision for vehicles and it does not work either.
```local DisableCollision = memory.scan("48 8B D1 49 8B CA ? ? ? ? ? 48 8B D1 49 8B CA") - 2
local backupcol = 0
local nocollisionveh = menu.my_root():toggle("Disable Collision", {}, "", function(on)
    if on then
        backupcol = memory.read_ubyte(DisableCollision)
        memory.write_ubyte(DisableCollision, 0xEB)
    else
        memory.write_ubyte(DisableCollision, backupcol)
    end
end)```

**Comment by Sainan** [comment]
Your explanation is nonsensical. This is a bytepatch, not a hook. Also, what exactly is the point of this "disable collision for vehicles" patch? Stand already has a builtin feature for this (`vehnocol`), it would seem wiser to simply use that.

**Comment by Polyester-ak-Parci** [comment]
> Ваше объяснение бессмысленно. Это байтпатч, а не хук. Кроме того, в чем именно смысл этого патча «отключение столкновений для транспортных средств»? В Stand уже есть встроенная функция для этого ( `vehnocol`), было бы разумнее просто использовать ее.



> Your explanation is nonsensical. This is a bytepatch, not a hook. Also, what exactly is the point of this "disable collision for vehicles" patch? Stand already has a builtin feature for this (`vehnocol`), it would seem wiser to simply use that.

yes. in the example that I have given here, this is a byte patch. I need the ability to write to any place in memory to implement functions that are not in the stand. and I want to realize them for myself. just please return the ability to write to any place in memory. in any case, it gives more options for the lua api. if you don't want it to hurt other users who don't understand what this feature does, just hide it as I mentioned earlier.

**Comment by Sainan** [comment]
You still have not given any reason for why this is needed.

**Comment by Polyester-ak-Parci** [comment]
> You still have not given any reason for why this is needed.

What reasons is good for u?

**Comment by Sainan** [comment]
Tell me a problem you can't solve by any means other than to write to executable bytecode sections.

**Comment by Polyester-ak-Parci** [comment]
> Tell me a problem you can't solve by any means other than to write to executable bytecode sections.

Hook game function

**Comment by Sainan** [comment]
That's not a problem

**Comment by Polyester-ak-Parci** [comment]
> That's not a problem

That's main problem for me

**Comment by Sainan** [comment]
As I've already told you, you can simply use the builtin Stand feature to disable vehicle collision. :)

**Comment by MihaiStreames** [comment]
...but what if they don't want to only disable vehicle collision and run code that is EXTERNAL to stand?

**Comment by Sainan** [comment]
That would be a security risk. And I don't see a good reason for it.
