### ISSUE TITLE
Random costumes will encounter invalid costumes, causing other players to crash

### ISSUE THREAD

**Issue by latiao-1337** [calamity-inc/Stand-Feedback#11]
- **Obvious problem description**
Random costumes will encounter invalid costumes, causing other players to crash
- **Steps to reproduce**
This problem is probabilistic and requires clicking Self>Appearance>Outfit>Wardrobe>Prefabricated Outfits>Current Model: Random
- **Sufficient context**
N/A

**Comment by Sainan** [comment]
Could you please share the outfit that you randomly generated which caused this issue?
