### ISSUE TITLE
spawn vehicles

### ISSUE THREAD

**Issue by Lechom** [calamity-inc/Stand-Feedback#111]
being able to spawn any vehicle in front of an other player via the players tab.

**Comment by inxanedev** [comment]
You can already do this by using "Issue Commands on [player]'s behalf"

In the command box, type "as [player name] bmx" for example, to spawn a BMX at their location.

**Comment by awaseru** [comment]
^

**Comment by Lechom** [comment]
> ^

it would be easier tho if you could spawn them infront of a player in player > friendly > vehicle then spawn vehicle like you can for yourself with the spawner section, Like a list of the vehicles with dlc, sports and so on. So you dont have to type everytime and make it much easier.
