### ISSUE TITLE
Launchpad button to kill GTA

### ISSUE THREAD

**Issue by mochawoof** [calamity-inc/Stand-Feedback#129]
**Is your feature request related to a problem? Please describe.**
When I close GTA normally, often the process stays open and I can't relaunch it.

**Describe the solution you'd like**
A single button in the launchpad to kill all running GTA processes would be very useful.

To avoid cluttering the launchpad menu the button could be put in the Advanced menu.

**Describe alternatives you've considered**
Closing it manually via the task manager works, but it takes time and time is money.

**Comment by nuggettowin** [comment]
press u > type “yeet”?

**Comment by mochawoof** [comment]
> press u > type “yeet”?

The window closes completely like normal but the PROCESS stays present in task manager as if the game was still running.

**Comment by nuggettowin** [comment]
¯\_(ツ)_/¯  was just a thought. had that issue before that yeet seemed to resolve.
