### ISSUE TITLE
Give an option to go back into a session that someone kicked you from

### ISSUE THREAD

**Issue by PlayboiCartiFan420** [calamity-inc/Stand-Feedback#130]
Whenever you get kicked from a session by a modder, you should be given the option to be put back into the session. This is good because when a modder love letter kicks you it's very annoying and it would be nice to be able to go back into the session and kick or crash the modder who kicked you.

**Comment by nuggettowin** [comment]
online > session > automatically rejoin desynced sessions

**Comment by Sainan** [comment]
`rejoin` also works.
