### ISSUE TITLE
Session multiplexer / Job populator or inviter

### ISSUE THREAD

**Issue by mehgancangweh** [calamity-inc/Stand-Feedback#132]
**Is your feature request related to a problem? Please describe.**
nuh

**Additional context**
Would be a cool things to see this in stand

**Comment by isytrana** [comment]
what the fuck is session multiplexer? describe what u want damnit

**Comment by nuggettowin** [comment]
if i’m understanding based on existing implementations of “multiplexer”: Makes your session much more visible to other players by submitting multiple sessions to the matchmaking server. High values generally fill your session up in seconds

**Comment by mehgancangweh** [comment]
[Online > Session > Player Magnet](https://stand.sh/focus#Online%3ESession%3EPlayer%20Magnet)
We up gang lets go even though required to be host
