### ISSUE TITLE
lua hotkey issue

### ISSUE THREAD

**Issue by Asuka-Tech** [calamity-inc/Stand-Feedback#134]
A good issue report has _at least one_ of these:
- **Obvious problem description**
  - after injecting stand , non of my hotkeys in lua scripts are existing/loaded, i have to manually restart the scripts and my hotkeys reappear, the issues affects all lua scripts.
- **Steps to reproduce**
  - set a hotkey for a function in lua script , restart the game and let stand inject on startup , the hotkey created will be missing untill u restart the script.

**Comment by Sainan** [comment]
I am unable to reproduce this behaviour.
