### ISSUE TITLE
Custom DLC Problems

### ISSUE THREAD

**Issue by mxdpinky** [calamity-inc/Stand-Feedback#137]
Using the same Custom DLCs before was working till like 10-20 different loaded cars, since the newest GTA DLC the game often just crashes at 2-3 loaded cars.
Also some Cars just kill me because I'm sitting in them, though I have Godmode active (Same cars had no problems before the newest DLC by GTA)

- Example 1: I spawn 3 different Koenigseggs (all worked great before the update) and want to take some pictures. After a minute or so, the game just crashes
- Example 2: I spawn a Lamborghini Huracan (also worked great before the update), sit in it to customize it and suddenly die, although i have Godmode activated. I respawn, enter the car again, same problem again. Deleting the car and spawning it again doesnt fix it.

**Comment by Sainan** [comment]
I have no problem loading multiple custom DLC vehicles. Ensure your pools are properly adjusted.
