### ISSUE TITLE
Exception when accessing Saved Places menu

### ISSUE THREAD

**Issue by RSBlackWash** [calamity-inc/Stand-Feedback#139]
Exception detected when accessing the Saved Places menu, most teleports don't work, those with a z component in the saved file will work initially, but stop working if one without a z component is attempted.
Initially hovering over a location without a Z component does not displayed the AR pink line to the location, but hovering over one with a Z component does. After attempting to teleport to one of the non-Z locations, no pink line is drawn for any item.
Also breaks spawning vehicles from Garage.

Not resolved by unloading and re-injecting. Resolved be restarting game.

Saved places without z component were created using menu World -> Places -> Position -> Save Waypoint Position
Saved places with z component were created using World -> Places -> Position -> Save My Position

Manually added z component to all saved locations, re-started game, all now works as expected.

[01/07/2024 15:21:37] ---- ERROR INFORMATION BEGINS ----
Type: Caught ACCESS_VIOLATION while reading from 0000000000000028
Message: Caught an exception.
Stack Trace:
  00007FFB0BE62F7B (Stand 116.5, 1337694200742F7B)
  00007FFB0BCD2134 (Stand 116.5, 13376942005B2134)
  00007FFB0BCD22BE (Stand 116.5, 13376942005B22BE)
  00007FFB0BE001B4 (Stand 116.5, 13376942006E01B4)
  00007FFB0BE004B4 (Stand 116.5, 13376942006E04B4)
  00007FFB0BE9126F (Stand 116.5, 133769420077126F)
  00007FFB0BE9107C (Stand 116.5, 133769420077107C)
  00007FFB0BE9108C (Stand 116.5, 133769420077108C)
  00007FFBB1E7C101 (KERNELBASE.dll+000000000007C101): PackageIdFromFullName
  00007FFBB45F091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFBB45F091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[01/07/2024 15:21:37] ---- ERROR INFORMATION ENDS ----

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.

(For reference: https://github.com/calamity-inc/Soup/commit/5600f2b1b16abfbbb91be93ac6641154c7b9d322)
