### ISSUE TITLE
PTFX on Bone using LUA

### ISSUE THREAD

**Issue by 4Notoelo** [calamity-inc/Stand-Feedback#141]
The issue begins with START_NETWORKED_PARTICLE_FX_LOOPED_ON_ENTITY_BONE 

essentially on certain lua which utilities this what occurs is the following:

you can start and remove the ptfx effect as expected when the lua is active using buttons provided 

however when the lua is deactivated whilst having the effect attached onto the bone it does not remove the effect despite being able to toggle it when its on -- previously it removed them when the scripted effects was on and if the lua was toggled off it also removed the effect

this occurred after the latest stand patch 01/07/24

not only with that 

if you for example run this on a vehicle where it check for tire health then applies the effect to that particular tire it also retain the effect on the vehicle if the effect is on and the lua is triggered off but can be removed on and off if the script is running 

essentially across my updated as well as some outdated luas this is occurring on effects which are constantly looping on their own outside of any script  

I have some scripted effects which are correctly being removed as expected as in the previous stand patch they are not looped on their own but are within the script itself 

example of looped ("weap_xs_vehicle_weapons", "muz_xs_turret_flamethrower_looping")

example of non looped  ("weap_ch_vehicle_weapons", "muz_ch_tank_laser") -- this is still working for me as expected as again within the script i am looping this but the effects itself is not 

this is working fine if you for example attach to an object as in the script i have it set to remove the object therefore it removes that effect-- gain same as for any other effect script i have i also have it set to remove them however it does not 

i have so far checked 3095 and other older ones and this is present across all of them when it comes to looping for example the flamethrower effect and in the past it removed it fine

hope this makes sense i can provide video proof if necessary

or the issue could be to do with how the lua is being toggle off perhaps abruptly and missing to toggle things off correctly as before

**Comment by Sainan** [comment]
I ain't reading all that, but I'm assuming it's an issue with your Lua script.
