### ISSUE TITLE
force relay

### ISSUE THREAD

**Issue by Lechom** [calamity-inc/Stand-Feedback#145]
I thought stand users cant see ur ip now when enabling force relay connections, they still can tho

**Comment by Prisuhm** [comment]
because iirc stand makes a direct connection with them anyways so you can still see people IP's through relays

**Comment by Prisuhm** [comment]
> I thought stand users cant see ur ip now when enabling force relay connections, they still can tho

iirc stand makes a direct connection with them anyways so you can still see people IP's through relays. its not a bug

**Comment by Lechom** [comment]
> > I thought stand users cant see ur ip now when enabling force relay connections, they still can tho
> 
> iirc stand makes a direct connection with them anyways so you can still see people IP's through relays. its not a bug

https://discord.com/channels/956618713157763072/956618713581387806/1257640747780538472

**Comment by Prisuhm** [comment]
> > > I thought stand users cant see ur ip now when enabling force relay connections, they still can tho
> > 
> > 
> > iirc stand makes a direct connection with them anyways so you can still see people IP's through relays. its not a bug
> 
> https://discord.com/channels/956618713157763072/956618713581387806/1257640747780538472

ah wasnt aware it was removed and reimplemented, ignore what I said then
