### ISSUE TITLE
Add a toggle option to disable all options in the Info Overlay

### ISSUE THREAD

**Issue by TCRoid** [calamity-inc/Stand-Feedback#150]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to temporarily disable the Info Overlay, but I have to turn off each of these options one by one, and then turn them back on one by one, which is quite troublesome.

**Describe the solution you'd like**
Add a toggle option to disable Info Overlay display.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by Sainan** [comment]
Game > Screenshot Mode ?

Stand > Apply Default State | Stand > Profiles ?
