### ISSUE TITLE
Problem with function: Max Columns

### ISSUE THREAD

**Issue by Lirniri** [calamity-inc/Stand-Feedback#151]
When setting the transparency in: Standard > Settings > Appearance > Colors > Focused Right-Bund Text Color. Column displays highlighting text outside of column
![GTA5_4PSRjifTl9](https://github.com/calamity-inc/Stand-Feedback/assets/106456219/9ae6dd59-60a9-421b-b85a-1b7244133eae)

**Comment by Sainan** [comment]
You can't set a transparency on the text colour? But I can see from your image, that the cursor border is drawn in all columns. This issue will be fixed.
