### ISSUE TITLE
"Thousands Separator For Money" causes abnormal display of mobile banking

### ISSUE THREAD

**Issue by Yuko1997** [calamity-inc/Stand-Feedback#152]
Online > Enhancements > Thousands Separator For Money，After enabling, the balance display in mobile banking will become abbreviated

like this
![20240704232751](https://github.com/calamity-inc/Stand-Feedback/assets/135049518/762dab34-1c3d-4ac8-9eb2-c2ab3d970425)

Is this behavior intentional? If not, please fix it. Thanks.

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
