### ISSUE TITLE
Occurs when the menu.list is closed in Lua Scripts

### ISSUE THREAD

**Issue by Lirniri** [calamity-inc/Stand-Feedback#153]
[04.07.2024 22:26:30] ---- НАЧАЛО ИНФОРМАЦИИ ОБ ОШИБКЕ ----
Type: Caught ACCESS_VIOLATION while reading from 0000000000000060
Message: Произошла какая-то ошибка
Stack Trace:
  00007FFC5544122B (Stand 116.7, 133769420045122B)
  00007FFC5543D022 (Stand 116.7, 133769420044D022)
  00007FFC5569895F (Stand 116.7, 13376942006A895F)
  00007FFC55692E65 (Stand 116.7, 13376942006A2E65)
  00007FFC55698F3C (Stand 116.7, 13376942006A8F3C)
  00007FFC55720FD1 (Stand 116.7, 1337694200730FD1)
  00007FFC556A6924 (Stand 116.7, 13376942006B6924)
  00007FFC556A6972 (Stand 116.7, 13376942006B6972)
  00007FFC558070FE (Stand 116.7, 13376942008170FE)
  0000029638ABA59C
  00000294BDDE8750
  00000294BDDE8750
  00007FF776FE30CB (GTA5.exe+00000000017130CB, 00007FF6391330CB)
  0000000000001368
  0000000000001368
Script VM:
  Executing Script: AM_MP_PROPERTY_EXT
  Executing Operation: Native 0xA5EDC40EF369B48D / 0x4F8644AF03D0E0D6 / 0xEE68096F9F37341E
[04.07.2024 22:26:30] ---- КОНЕЦ ИНФОРМАЦИИ ОБ ОШИБКЕ ----

**Comment by Sainan** [comment]
Could you provide an example Lua script to reproduce this?

**Comment by Lirniri** [comment]
Have you already fixed this problem? Should I still submit the script?
