### ISSUE TITLE
Lock Weapons command names broken

### ISSUE THREAD

**Issue by Davus0717** [calamity-inc/Stand-Feedback#154]
- **Problem Description**
  - I expect each command in `Lock Weapons` to include the weapon name, further: the feature to work at all. That's not the case.
- **Sufficient context**
  - Since either 116.6 or 116.7 the commands for "Lock Weapons" all miss the weapon name, which is essential for the feature to work properly.
  - Examples:
    - `Self>Weapons>Lock Weapons>Melee Weapons>Knife>Knife` used to have the command `lockweaponknife`, now it's `lockweapon` (applies to all weapons)
    - `[...]>Melee Weapons>Knife>Weapon Tint` used to have the command `lockweaponknifetint`, now it's `lockweapontint` (applies to all weapons)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
