### ISSUE TITLE
[116.7] Issue with loading Rainbow Mode color settings

### ISSUE THREAD

**Issue by shadow7483147** [calamity-inc/Stand-Feedback#155]
### **Obvious problem description**
- Settings that have a Rainbow Mode saved to the profile do not load properly
- This has been an issue for a while, since before Stand 100
```
[7/4/2024 4:16:29 PM] Failed to set state for Stand>Settings>Appearance>Notifications>Border Colour: invalid string position
```

### **Steps to reproduce**
1. [Settings > Appearance > Notifications > Border Color > Rainbow Mode](https://stand.gg/focus#Stand%3ESettings%3EAppearance%3ENotifications%3EBorder%20Colour%3ERainbow%20Mode)
2. Go to the context menu for Rainbow Mode and Save State.
3. Load the currently active profile again.

### **Profile in question**
```
			Notifications
				Border Colour: 
					Rainbow Mode: 2
				Flash Colour: 700070FF
				Background Colour: 0000008C
```

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
