### ISSUE TITLE
Hoisted Tag not in right order

### ISSUE THREAD

**Issue by johnny01pl** [calamity-inc/Stand-Feedback#157]
Hi, I noticed that in Players > Settings > Hoisted Tags if I mark the Tags that should be priority in player list, they are not prioritized.

I will send a screenshot.
![iq1H3ir](https://github.com/calamity-inc/Stand-Feedback/assets/174791315/735ee88f-778a-4bec-b2ee-11705e6d4ba6)
![playerlist](https://github.com/calamity-inc/Stand-Feedback/assets/174791315/76672623-24ff-41d3-94a3-e8eed3ad533f)

**Comment by Sainan** [comment]
Could you clarify what you mean? I don't see any problems in your provided screenshots.

**Comment by johnny01pl** [comment]
I mean, few updates ago when i hit checbox ''ME" in hoisted tags, I was the first on the playerlist and 2nd was friend, Host is 10th in position in hoisted tags but still is 1st on the player list and i am 3rd.

**Comment by Sainan** [comment]
We didn't change anything about the way hoisted tags work recently. The way it works is that if a player has a tag you have selected to be hoisted, they will be put before player who do not have a tag you have selected to be hoisted. And that seems to be working fine.
