### ISSUE TITLE
Gift car feature has disappeared from menu 

### ISSUE THREAD

**Issue by Jmitty2182** [calamity-inc/Stand-Feedback#162]
A good issue report has _at least one_ of these:
- **Obvious problem description**
  - For example: "I expected Immortality to make me immortal, but I still died."
- **Steps to reproduce**
- **Sufficient context**
  - For things related to detections, the things in the parentheses.
  - For false-positives, a log of the event.
  - Stack trace, if applicable, and if Stand's DLL is a major part of it.

**Comment by shadow7483147** [comment]
> ## Stand 116.3
> - Removed gift vehicle and ban kick as they have been patched

Not a bug.
