### ISSUE TITLE
No Recoil, No Spread and No Spooling don't stick with game restart

### ISSUE THREAD

**Issue by pedrodanielsantos** [calamity-inc/Stand-Feedback#169]
The **No Recoil**, **No Spread** and **No Spooling** features under _Self > Weapons_ need to be disabled and re-enabled to actually work.

I've got them all saved to my profile and yet every time I restart the game, even while still toggled on they aren't taking effect.

To reproduce simply toggle them on, save to profile and restart the game (forcequit command also does it).

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
