### ISSUE TITLE
AUTHENTICATION METHOD

### ISSUE THREAD

**Issue by Manolo0987** [calamity-inc/Stand-Feedback#17]
**Is your feature request related to a problem? Please describe.**
yes, if you lose your key you have to rebuy stand, so with this method, you could recover it easily and safetly, nobody can access to your phone or to your authenticator software

**Describe the solution you'd like**
it would be nice if you add a authentication method trough authenticator software or sms

**Describe alternatives you've considered**
?

**Additional context**
?

**Comment by AXOca** [comment]
One aspect of your feature request is already available. As of April 26, 2024, you can link your Account ID to your phone number on the Respire platform.

To update this, simply visit: [stand.gg](https://std.gg/account-id)
