### ISSUE TITLE
session browser bug

### ISSUE THREAD

**Issue by 911xiaotian** [calamity-inc/Stand-Feedback#170]
![J$CX8F9`IPD2V`ZT} X8 PD](https://github.com/calamity-inc/Stand-Feedback/assets/174970284/d024f650-70d4-410a-89e6-34fa3fb0cfeb)
He seemed to have a problem in browsing ASIA, no matter how many people only show 20? Intersection Intersection

**Comment by Sainan** [comment]
It seems like a lot of these hosts are spoofing the player count. It's not really possible to reconcile this. You'll just have to request the member list and check yourself.

**Comment by 911xiaotian** [comment]
what






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月8日(星期一) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [calamity-inc/Stand-Feedback] session browser bug (Issue #170)














 
Closed #170 as not planned.
