### ISSUE TITLE
Magic Bullets of AIMBOT

### ISSUE THREAD

**Issue by 911xiaotian** [calamity-inc/Stand-Feedback#172]
My understanding is that Magic Bullet is an unwanted Aimbot. Similar to Silent AIM, it can really add a Silent AIM. It can be more convenient to kill the enemy when doing tasks. The best cheat first means asking! get good get stand!

**Comment by shadow7483147** [comment]
It may be helpful to post your request in your native language. Your English is not easily understood.

The only thing Magic Bullets does is create a bullet between you and your target's head when you shoot. Unfortunately, this can be detected as duplicated or "double-tapped" bullets. I would prefer it actually modify the aim vector without changing your camera angle, like a proper silent aim.

Also, guns in GTA typically are not hitscan. Guns just have extremely fast projectile speeds that it becomes *effectively* hitscan, save for the Musket and Railgun (which is ironically slower than bullets.) This means you may need to lead your shot slightly when aiming long distances, and Stand's aim does the opposite when smoothing. It lags behind the target when not using Magic Bullets.
