### ISSUE TITLE
Driveby Weapons' ridiculous fire rate with "Skip Reloading"

### ISSUE THREAD

**Issue by ghost** [calamity-inc/Stand-Feedback#178]
Description:
   When "Skip Reloading" is turned on, any gun (not throwables) will have a ridiculous fire rate, while inside of a vehicle
(In other words, the firerate will feel as if your gun has become a minigun)

How To Reproduce:
1. Enable "Skip Reloading" in "Self > Weapons"
2. Get into a vehicle
3. Equip any gun (not a throwable, like grenades)
4. Hold the "Fire" key
5. Watch the fire rate and ammo consumption

Additional Information
The bug only occurs when inside of a vehicle and using any of your owned guns.
Can be any seat in a vehicle, as long as you have access to your own weapons.
Doesn't occur when on foot.

**Comment by Sainan** [comment]
That's how GTA works. Set a correlation if it bothers you.
