### ISSUE TITLE
Super Melee causes lag spikes upon activation

### ISSUE THREAD

**Issue by TheApplePro** [calamity-inc/Stand-Feedback#181]
I have noticed that the more objects I surround myself with, more frame drops occur when Super Melee is active.
Also the level of the Super Melee _kind of_ correlates to the amount of frame drops I experience.
For example (see top left for fps counter):

- Super Melee disabled:

![Képernyőkép 2024-07-09 103254](https://github.com/calamity-inc/Stand-Feedback/assets/139914091/cbaf2b30-f8c2-4e8e-8f33-832178701adb)

- Super Melee 10:

![Képernyőkép 2024-07-09 103550](https://github.com/calamity-inc/Stand-Feedback/assets/139914091/fcae78d9-145b-4eed-ba3c-9d0ee349d1c4)

**Comment by awaseru** [comment]
i am not able to reproduce any noticeable performance loss. the power is only relevant when you attack something. maybe placebo.
