### ISSUE TITLE
"Be Alone" Triggering automatic desync rejoin

### ISSUE THREAD

**Issue by DMC1134** [calamity-inc/Stand-Feedback#182]
Stand Version: 116.8.

Issue: Using the "Be Alone" Option, Online > Session > Be Alone, triggers "Automatically rejoin Desynced Sessions", Online > Session > Automatically rejoin Desynced Sessions > Automatically rejoin Desynced Sessions, putting me back in the lobby with everyone again.

**Comment by Sainan** [comment]
Can't reproduce.
