### ISSUE TITLE
Bypass Profanity Filter doesnt work properly

### ISSUE THREAD

**Issue by Deyyzy** [calamity-inc/Stand-Feedback#183]
![stand](https://github.com/calamity-inc/Stand-Feedback/assets/175124256/29c19a4d-8916-428b-b582-fe97917132da)
i had the bypass on but for sum reason some words still get censored that arent profanity but still shouldnt the bypass any word?

**Comment by Lechom** [comment]
The option only makes your words not censored for other players.

**Comment by Deyyzy** [comment]
> The option only makes your words not censored for other players.
omg dumbass of the day, i said it doesnt work properly because bypass profanity is supposed to bypass any censor if i am correct

**Comment by Sainan** [comment]
Read the help text, "dumbass"

![image](https://github.com/calamity-inc/Stand-Feedback/assets/63328889/0bd9ee78-3339-41a4-b65e-e26d5c4ab6ad)
