### ISSUE TITLE
Kick false flags due to script host

### ISSUE THREAD

**Issue by Decuwu** [calamity-inc/Stand-Feedback#19]
Bug Description:
After kicking someone who attacked you with script host, every person to get script host after will flag as trying to kick you.

How to replicate:
I had a friend use smart kick against me which gave them script host, after kicking them (as host), script host went to someone else and flagged as them trying to kick me

Media:
- sorry for poor quality, i used sharex to record it but what is happening should be visible. Also 10mb limit so it's trimmed from the full length where i was kicking people that got flagged to show it would bounce from player to player

https://github.com/calamity-inc/Stand-Feedback/assets/112495774/cb5e0e72-7618-4c57-b829-be0fa59f0455

**Comment by Sainan** [comment]
Your details don't quite add up. N6 would be rope crash, and if the person who sent this to you was innocent, then they should've crashed due to having had the rope synched to them.

**Comment by Decuwu** [comment]
i can create another video of doing it from beginning to end but im not sure how to upload it when github only allows 10mb max uploads. i'll see what i can do!

**Comment by Decuwu** [comment]
I start with asking .Emilia to use Smart Kick on me, she gets script host through using it and i love letter kick her, then the script host switches to a new player and they get flagged for Kick Events. 

I didn't realise that the 1st video i sent displayed a crash event, that doesn't now as im recreating it, only kick events. 

I'm not sure if you need to be host for this to start false flagging but each time i've seen it i've been host.


https://github.com/calamity-inc/Stand-Feedback/assets/112495774/0ee8a306-fb25-4e12-8d9a-614fe35531c6

**Comment by Sainan** [comment]
Do you have a log of this "Kick Event"? I'm not aware of any instance where we don't also specify a codename (like N6) to clarify what exactly the event is about.

**Comment by Decuwu** [comment]
i dont believe im logging kicks by default, i can enable it and get back to you with the logs

**Comment by Decuwu** [comment]
[06/06/2024 14:42:19] Kick Event from -Fr4g-

![image](https://github.com/calamity-inc/Stand-Feedback/assets/112495774/641e2748-859b-4874-b933-e421495a4b90)

unless there are other logs, log.txt and the console both only show this

**Comment by Sainan** [comment]
Might be fixed in the next update.
