### ISSUE TITLE
Cant use this: Stand > Settings > Appearance > Colours > AR Colour > Enter Hex Code

### ISSUE THREAD

**Issue by IlIlIlIIlIlIlIl** [calamity-inc/Stand-Feedback#2]
![GTA5_auvktIo9pf](https://github.com/calamity-inc/Stand-Feedback/assets/107168271/b118b71d-fb1c-45b5-8e82-d6843497bba8)

i cant change ar colour with hex code

**Comment by Sainan** [comment]
I am unable to reproduce this behaviour.

**Comment by AXOca** [comment]
If it says:"ar could mean multiple things", I would assume you have some kind of lua script which for some reason uses the same command for something.

**Comment by IlIlIlIIlIlIlIl** [comment]
> If it says:"ar could mean multiple things", I would assume you have some kind of lua script which for some reason uses the same command for something.

I was trying it with default state, but after restarting my game and trying it again its working now so thats weird.
