### ISSUE TITLE
A proper Click UI.

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#202]
I personally like the fact that Stand supports Mouse as a way to naviguate through the menu.
However, the UI (in my opinion) doesn't quite fit the mouse support.
If possible, doing a proper click UI for mouse users would be amazing.

Here is something I quickly did in Paint as a "concept art".
![ClickGUI-ConceptArt](https://github.com/user-attachments/assets/584adbb2-2dae-46e8-81c4-5a7d42f04cc9)

**Comment by isytrana** [comment]
I also did an alternative style since i just noticed the first concept looked a lil bit too much of the normal stand
![concept art of click gui stand](https://github.com/user-attachments/assets/d200e177-0f64-4a40-a307-8d98fafe789d)

**Comment by Sainan** [comment]
Stand > Settings > Appearance > Max Columns
