### ISSUE TITLE
menu.trigger_commands("upgradeveh" .. player_name)

### ISSUE THREAD

**Issue by Baiawai** [calamity-inc/Stand-Feedback#208]
When I run this command I receive a notification that seems like it shouldn't be there.
- **Steps to reproduce**
menu.trigger_commands("upgradeveh" .. player_name)

![20240714192707_1](https://github.com/user-attachments/assets/87865b53-2573-47d6-98d5-0ec4b8429ce2)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
