### ISSUE TITLE
Problem since the latest version 116.9 with load()

### ISSUE THREAD

**Issue by Lama-sticot** [calamity-inc/Stand-Feedback#214]
As part of a script to share with friends to avoid sending it each time I had set up a script to call the code from a web server and use the load() function from the update that returns me as an error: 

` [string "test.pluto"]:11: attempt to call a nil value (global 'load')
stack traceback:
        [string "test.pluto"]:11: in function <[string "test.pluto"]:10>
        [C]: in function 'xpcall'
        [string "Stand Lua Runtime"]:22: in function 'internal_xpcall_ioiqocsdvv'
        [string "Stand Lua Runtime"]:28: in function <[string "Stand Lua Runtime"]:27>`
        
here's an example of the code I use to make the call and the load : 

`
  async_http.init("https://pastebin.com/raw/psF9ALi5", nil, function(data)
                   local func = load(data)
                   if func then
                       func()
                   end
               end)
               async_http.dispatch() 
               `

I tried the same code on 116.8 and it works perfectly.

ty in advance for your reply :)

**Comment by Sainan** [comment]
Data and code should be kept separate. We do not support this kind of use-case.

**Comment by Lama-sticot** [comment]
so it's normal for this one to give me an error? it's a modification on your part so that it works like here? because as I said, it works on the old version (116.8).
