### ISSUE TITLE
divide/ key binding issue

### ISSUE THREAD

**Issue by ghost** [calamity-inc/Stand-Feedback#226]
After the divide/ key on the Numpad is bound to the stand function, if I press the another divide key on the main keyboard, the function will also be trigger.
When binding keys, can let stand distinguish divide/ key and Numpad divide/ key

**Comment by Inkmaveil** [comment]
![Uploading divide.jpeg…]()

**Comment by Inkmaveil** [comment]
![Uploading divide.jpeg…]()

**Comment by Inkmaveil** [comment]
![Uploading divide.jpeg…]()

**Comment by Sainan** [comment]
I'm afraid there's no way to tell them apart with the Windows API.
