### ISSUE TITLE
False Co-Loading Detection

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#227]
I got no idea how to reproduce it, but when I get detected as a Stand User, it marks "Stand User (Co-Loading)", even though I am not.
I noticed the false co-loading thing when I went to Online > Protections :

![image](https://github.com/user-attachments/assets/c2d4bb03-ce09-40bc-8a32-515f3a2070e0)

I got no idea how to reproduce or anything, I am loading just Stand and loaded Stand alone on this game instance.

![image](https://github.com/user-attachments/assets/1daff03c-b8da-42c6-b3e0-2d7db3748870)

**Comment by Xenorhaste** [comment]
[coloading detection2.txt](https://github.com/user-attachments/files/16288526/coloading.detection2.txt)
[coloading detection1.txt](https://github.com/user-attachments/files/16288527/coloading.detection1.txt)
[coloading detection3.txt](https://github.com/user-attachments/files/16288529/normal.txt)
those three profiles for example trigger it for no reason.

**Comment by zfdfgffretherrfw** [comment]
do you use fsl ?

**Comment by isytrana** [comment]
i don't use fsl @zfdfgffretherrfw

**Comment by Sainan** [comment]
I've tried loading this "coloading detection1.txt", and Stand still does not think I'm co-loading. So, can't reproduce.
