### ISSUE TITLE
after [116.10] i get Error in my script : CommandUniqPtr does not hold a command

### ISSUE THREAD

**Issue by TheaterChaos** [calamity-inc/Stand-Feedback#229]
after the new stand update i got this error. if i attach a "menu.toggle_loop" function after something and i will run it it runs 1 time and then this error comes and the loop stops. 

Commandname = menu.attach_after(commandref, menu.toggle_loop(menu.shadow_root(),  "name", {}, "", function()
util.toast("Test")
end))

Full Error:
[string "Stand Lua Runtime"]:63: CommandUniqPtr does not hold a command
stack traceback:
        [C]: in metamethod 'index'
        [string "Stand Lua Runtime"]:63: in function <[string "Stand Lua Runtime"]:57>
        [C]: in function 'xpcall'
        [string "Stand Lua Runtime"]:22: in function 'internal_xpcall_ioiqocsdvv'
        [string "Stand Lua Runtime"]:28: in function <[string "Stand Lua Runtime"]:27>

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
