### ISSUE TITLE
Launching Stand causes error message to come up

### ISSUE THREAD

**Issue by drizno** [calamity-inc/Stand-Feedback#23]
I open GTA V with Stand and a prompt opens noting an error

[6/6/2024 12:31:09 PM] ---- ERROR INFORMATION BEGINS ----
Type: Uncaught INT_DIVIDE_BY_ZERO
Message: The game had a fatal error and may need a restart now.
Stack Trace:
  00007FF6CF8EF25E (GTA5.exe+000000000065F25E, 00007FF6FEACF25E)
  00007FF6D00CF25B (GTA5.exe+0000000000E3F25B, 00007FF6FF2AF25B)
  00007FF6D08C3449 (GTA5.exe+0000000001633449, 00007FF6FFAA3449)
  00007FF6D08C2C7F (GTA5.exe+0000000001632C7F, 00007FF6FFAA2C7F)
  00007FF6CF2B76A4 (GTA5.exe+00000000000276A4, 00007FF6FE4976A4)
  00007FF6CF2B0D8B (GTA5.exe+0000000000020D8B, 00007FF6FE490D8B)
  00007FF6D08C2888 (GTA5.exe+0000000001632888, 00007FF6FFAA2888)
  00007FF6CF291494 (GTA5.exe+0000000000001494, 00007FF6FE471494)
  00007FF6D059904F (GTA5.exe+000000000130904F, 00007FF6FF77904F)
  00007FF6D0AB5DCC (GTA5.exe+0000000001825DCC, 00007FF6FFC95DCC)
  00007FFBD7AA257D (KERNEL32.DLL+000000000001257D): BaseThreadInitThunk
  00007FFBD862AA48 (ntdll.dll+000000000005AA48): RtlUserThreadStart
  00007FFBD862AA48 (ntdll.dll+000000000005AA48): RtlUserThreadStart
Action: Continuing execution at next instruction.
[6/6/2024 12:31:09 PM] ---- ERROR INFORMATION ENDS ----

This occurs every time I open the game without fail

**Comment by drizno** [comment]
PROFILE:
Finished Tutorial: Yes
Understands Commands: Yes
Understands Sliders: Yes
Understands Profiles: Yes
Understands Context Menu: Yes
Understands Controller Open/Close: Yes
Prompted For Controller Disables: Yes
Understands Command Chaining: Yes
Tree Compatibility Version: 53
Self
	Movement
		Graceful Landing: On
	Appearance
		Walk Style: Tough Guy (Male)
		Preserve Walk Style During Combat: On
		No Blood: On
		Lock Wetness: On
	Weapons
		Infinite Ammo: On
		Skip Reloading: On
		No Spread: On
		No Recoil: On
		No Spooling: On
		Rapid Fire Vehicle Weapons: On
		Instant Lock-On: On
		Instant Proximity Mine Detonation: On
		Total Freedom: On
		Increased Sticky Limit: On
		Increased Flare Limit: On
	Immortality: On
	Gracefulness: On
	Glued To Seats: On
	Set Wanted Level: 5
	Infinite Stamina: On
	No Combat Roll Cooldown: On
	Respawn At Place Of Death: On
Vehicle
	Los Santos Customs
		Appearance
			License Plate
				Text: 87ZBM229
	Movement
		Super Drive
			Super Drive: On
		Speed Limit (KMH): 10000
		No Turbulence: On
		Engine Power Multiplier: 2.00
		Lessen Tyre Burnouts: On
		Smooth Coasting: On
	Indestructible: On
	Permanent Mint Condition: On
	Can't Be Locked On: On
Online
	Transitions
		Matchmaking
			Asset Hashes
				Fix Asset Hashes: On
	Enhancements
		Disable Idle/AFK Kick: On
		Disable LSC Restrictions: On
		Phone Animations: On
		Speed Up Dialing: On
		Disable Death Barriers: On
		Disable Mechanic Cooldown: On
		Disable VIP Work Cooldown: On
		Disable Suicide Cooldown: On
		Disable Passive Mode Cooldown: On
		Disable Orbital Cannon Cooldown: On
		Disable Kosatka Missile Cooldown: On
		Disable Kosatka Missile Range Limit: On
		Disable Nano Drone Ability Cooldown: On
		Disable Business Battle Music: On
		Disable Event End Countdown Audio: On
		Allow Pausing: On
		Allow Weaponised Vehicles In Passive Mode: On
		Disable Forced RC Perspective: On
		Bypass Interior Restrictions: On
		Bypass Interaction Menu Barriers: On
		Bypass Casino Region Lock: On
		Bypass Time Trial Vehicle Suitability: On
		Notify On Commendation: On
		Disable Daily Expenses: On
		Ensure Clean Races: On
	Quick Progress
		Casino
			Always Win Blackjack: On
			Roulette Outcome: 36
		Nightclub Popularity
			Lock Nightclub Popularity: On
	Reveal Off The Radar Players: On
	Reveal Invisible Players: On
World
	Atmosphere
		Override Weather: Clouds
Game
	Rendering
		Distance Scaling: 1.50
	Unlocks
		Reveal Entire Map: On
	Minimap
		Sleek Minimap: On
	Early Inject Enhancements
		Memory Pool Size (MB): 2147
		Set Game To High Priority: On
Stand
	Settings
		Appearance
			Colours
				Primary Colour: 000000FF
				HUD Colour: 000000FF
				AR Colour: 000000C7
				Minigame Colour: 000000FF
	ASI Mods
		Settings
			Deceive Online Checks: On
		dxgi: On
		GTAV.HeapAdjuster: On
		Menyoo: On
		NVE: On
		OpenIV: On

**Comment by Sainan** [comment]
Could you please put your profile in a code block so I can actually load it

**Comment by Sainan** [comment]
But I do see you have some ASI mods loaded. Could you try disabling those and seeing if it still happens?

**Comment by drizno** [comment]
Disabled the ASI mods but I still received the same error message.
This the profile:
[Online.txt](https://github.com/user-attachments/files/15664081/Online.txt)

**Comment by Sainan** [comment]
I do not get this exception when loading your profile. Is it only when you early-inject? Do you load into Story Mode or Online?

**Comment by drizno** [comment]
Always load Story Mode first, with auto-inject on.

**Comment by Sainan** [comment]
I've loaded into SP with your profile and I still did not see this exception. Maybe try verifying your game files and ensure you have no unwanted DLLs in the game folder.
