### ISSUE TITLE
Unable to start job Unusual Event (G2) from xxxx

### ISSUE THREAD

**Issue by latiao-1337** [calamity-inc/Stand-Feedback#231]
- **Obvious problem description**
Unable to start job Unusual Event (G2) from xxxx
Unusual Event (G2) from xxxx
- **Steps to reproduce**
- **Sufficient context**
Select a job
Waiting for other players to join
start
Unusual Event (G2) from xxxx

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
