### ISSUE TITLE
disable nano drone ability cooldown doesnt work

### ISSUE THREAD

**Issue by Lechom** [calamity-inc/Stand-Feedback#234]
when enabling "disable nano drone ability cooldown" it still has the cooldown.

**Comment by Sainan** [comment]
Could you slightly clarify on this? The feature disables the cooldowns on shock, detonate, & boost.

**Comment by Lechom** [comment]
> Could you slightly clarify on this? The feature disables the cooldowns on shock, detonate, & boost.

i mean when you detonate it, theres still a cooldown to use the nano drone again
![Screenshot 2024-07-20 023536](https://github.com/user-attachments/assets/286598e1-d88f-450b-8ee8-438888cf31fa)

**Comment by Lechom** [comment]
thought the feature does that, cuz theres not a help text what it actually disables.

**Comment by Sainan** [comment]
I'm told the feature works as intended.
