### ISSUE TITLE
Update Bypass Message Filter

### ISSUE THREAD

**Issue by skateboardings** [calamity-inc/Stand-Feedback#240]
**Is your feature request related to a problem? Please describe.**
One thing I find frustrating is, sure, I can see and others can see MY messages unfiltered, but I cannot see theirs unfiltered. It gets pretty tough to figure out what they're actually saying

**Describe the solution you'd like**
An Update to Bypass Message Filter that allows me to see the unfiltered message (client-side or server)

**Describe alternatives you've considered**
Logs, Lua, etc.

**Additional context**
N/A

**Comment by Sainan** [comment]
Messages are censored by the sender, not the recipient.
