### ISSUE TITLE
infinite agency loading screen

### ISSUE THREAD

**Issue by Jeidremure** [calamity-inc/Stand-Feedback#241]
When I have the stand injected and I try to leave the agency with a helicopter or start a VIP contract mission that starts in a helicopter I get a stand alert telling me an infinite loading screen and well that's an infinite loading screen, when I remove it The stand does not have infinite load, I reinstalled the stand in case it was something I put in but it wasn't.
Steps: Try to exit the agency with a helicopter
With stand:
https://github.com/user-attachments/assets/1927600e-8dcb-4ca6-a68c-56bdc33f97ae
Without stand: I can't put the video because Github doesn't allow me, but when I click to go out with the helicopter it comes out perfectly without a loading screen

**Comment by Sainan** [comment]
Does this happen on default state?

**Comment by Jeidremure** [comment]
> Does this happen on default state?

Yes, as I said before, I even managed to reinstall the stand.

**Comment by Sainan** [comment]
Do you see any notifications such as "Unusual Event" or "Modded Event"?

**Comment by Sainan** [comment]
I see you say that you get a notification about "Infinite Loading Screen." Could you enable logging for this event, and share the log of the false-positive?

**Comment by Jeidremure** [comment]
> I see you say that you get a notification about "Infinite Loading Screen." Could you enable logging for this event, and share the log of the false-positive?

This is the log [21/07/2024 14:52:40] Pantalla de carga infinita de Jeidremureyt: Evento de script: {0: 247853458, 1: 0, 2: 0, 3: 0, 4: 0, 5: 1}

**Comment by Sainan** [comment]
Thanks, will be fixed in the next update.
