### ISSUE TITLE
add stat_set_int64 api

### ISSUE THREAD

**Issue by latiao-1337** [calamity-inc/Stand-Feedback#243]
**Is your feature request related to a problem? Please describe.**
add stat_set_int64

**Describe the solution you'd like**
I hope you can add the api for stat_set_int64 so that I can write int64 values ​​to stats like MPPLY_TOTAL_SVC

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Sainan** [comment]
Will be added in the next update.
