### ISSUE TITLE
Toggle box on left side

### ISSUE THREAD

**Issue by yKosa001** [calamity-inc/Stand-Feedback#246]
**Is your feature request related to a problem? Please describe.**
When the toggle buttons are on the right side of the mod menu. As I prefer them to be on the left side for better accessibility and aesthetics.

**Describe the solution you'd like**
I would like a feature that allows moving the toggle buttons to the left side of the mod menu, without affecting the position of the arrows. This would enhance my user experience by aligning the interface more with my personal preferences.

**Describe alternatives you've considered**
I have found a feature that moves the toggle buttons to the left side, but it also moves all the arrows in the menu. This is not ideal as I only want the toggle buttons to be relocated, not the arrows.

**Additional context**
Here are some screenshots to illustrate the current layout and the desired changes.
![image](https://github.com/user-attachments/assets/bbe71cfc-bbd7-4ae7-ba8f-b0bd101659e9)

**Comment by Sainan** [comment]
Stand > Settings > Appearance > Textures > Leftbound

**Comment by Lechom** [comment]
> Stand > Settings > Appearance > Textures > Leftbound

 I think he knows that but he means with that, that he only wants the toggle buttons to go to the left and not the arrows, when you enable leftbound, the arrows also go to the left.

**Comment by yKosa001** [comment]
> > Stand > Settings > Appearance > Textures > Leftbound
> 
> I think he knows that but he means with that, that he only wants the toggle buttons to go to the left and not the arrows, when you enable leftbound, the arrows also go to the left.

thats right, i know about that but i want arrows to stay on the right side.

**Comment by Sainan** [comment]
Looks a bit ugly if you ask me

![image](https://github.com/user-attachments/assets/7008b876-3410-479f-b9b7-8efcd2fe4f52)

![image](https://github.com/user-attachments/assets/4f40abf1-4c3f-43d9-9956-63995596809e)
