### ISSUE TITLE
vehicles parts getting off even with perma mint & vehicle god mod enabled

### ISSUE THREAD

**Issue by UnAneOnyme** [calamity-inc/Stand-Feedback#248]
- **Obvious problem description**
  - On some vehicles, some parts can detach even with perma mint and vehicle god mod enabled and they don't come back until you manually repair the vehicle
-**How to reproduce it**
  - **Enable perma mint and vehicle god mode, spawn a vehicle where it happens (i noticed it on a lot of F1 vehicles parts, i'm using a fully maxxed & customised BR8 and (i also noticed it can happen to pariah's hood with some super fast crashes but i couldn't reproduce it on purpose while i could with the BR8) but i guess it can happen on a lot more vehicles), Get at high speeds (personnaly BR8 with max engine reprog on x6.5 engine power via stand), crash into something and you should lose some parts**

Here's some screenshots of the issue, the top one is mint after repair, the bottom one is after a ~300kph crash
![image](https://github.com/user-attachments/assets/3d340fc6-05a7-48e6-9a8f-6019d6b4d028)
![image](https://github.com/user-attachments/assets/d50fbd85-31fb-404e-b2eb-98780ae27477)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
