### ISSUE TITLE
VPN Tag Issue

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#251]
I am using ProtonVPN, sometimes my ISP is "Proton AG" and Stand somehow doesnt detect it as a VPN, I dunno how the vpn detection works but there u go.

**Comment by Sainan** [comment]
Could you please share the VPN IP address that isn't detected?

**Comment by Sainan** [comment]
Well, I just realised "Proton AG" wasn't in the lists at all, so I just added that here: https://github.com/calamity-inc/soup-extra-data/commit/4acff1d6a60fef8902cf52c624be13953808ee3f

Your client will update this file automatically, but you can manually force an update by deleting `C:\ProgramData\Calamity, Inc\Soup\WebResource\9FA974DABAB96111D809977D40DC08961F6A4846` and reinjecting Stand.

Let me know if the issue persists.

**Comment by isytrana** [comment]
It works fine, thanks!
![image](https://github.com/user-attachments/assets/5d6aa1eb-b547-4e89-888c-d9c53946d0e0)
