### ISSUE TITLE
Max Tuning 

### ISSUE THREAD

**Issue by Xenorhaste** [calamity-inc/Stand-Feedback#252]
The Vehicle [Niobe] doesnt spawn with max tuning even if its enabled.
The command "Tune" doesnt do it either. it doesnt att the spoiler or anything else like Brakes, Engine, Spoiler or Transmission
it only says -1 and adds the Turbo and the Armor.

i guess this is due to the fact that the max tune would be the HWS upgrade which cause issues. but bc of that the Tune command just doesnt work at all on it
![image](https://github.com/user-attachments/assets/7593c4fd-2cb2-4e26-934d-453266d480eb)

Since it was working when it realesed and got fixed after a stand update. i guess it wont be enabled again, but that it aleast does the max it can apply if possible

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
