### ISSUE TITLE
Stand crash 

### ISSUE THREAD

**Issue by NickB926** [calamity-inc/Stand-Feedback#256]
Spamming the Invite to session button crashes the game 

[Log.txt](https://github.com/user-attachments/files/16404838/Log.txt) LOG

https://github.com/user-attachments/assets/dcde49f9-4bb2-4147-9fee-4874b253af45 Video Demonstration 

mainly this 

Message: Caught an exception.
Stack Trace:
  0000000000000000
  00007FF61AC74355 (GTA5.exe+0000000000444355, 00007FF7B6C94355)
  00007FFCC51E6A26 (Stand 24.7.8, 13376942006C6A26)
  00007FFCC51A599F (Stand 24.7.8, 133769420068599F)
  00007FFCC5254C3F (Stand 24.7.8, 1337694200734C3F)
  00007FFCC5254A4C (Stand 24.7.8, 1337694200734A4C)
  00007FFCC5254A5C (Stand 24.7.8, 1337694200734A5C)
  00007FFD6B18A521 (KERNELBASE.dll+000000000007A521): RegQueryInfoKeyA
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[7/28/2024 2:25:01 PM] ---- ERROR INFORMATION ENDS ----
[7/28/2024 2:25:01 PM] ---- ERROR INFORMATION BEGINS ----
Type: Caught ACCESS_VIOLATION (DEP at 0000000000000000)
Message: Caught an exception.
Stack Trace:
  0000000000000000
  00007FF61AC74355 (GTA5.exe+0000000000444355, 00007FF7B6C94355)
  00007FFCC51E6A26 (Stand 24.7.8, 13376942006C6A26)
  00007FFCC51A599F (Stand 24.7.8, 133769420068599F)
  00007FFCC5254C3F (Stand 24.7.8, 1337694200734C3F)
  00007FFCC5254A4C (Stand 24.7.8, 1337694200734A4C)
  00007FFCC5254A5C (Stand 24.7.8, 1337694200734A5C)
  00007FFD6B18A521 (KERNELBASE.dll+000000000007A521): RegQueryInfoKeyA
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[7/28/2024 2:25:01 PM] ---- ERROR INFORMATION ENDS ----
[7/28/2024 2:25:01 PM] ---- ERROR INFORMATION BEGINS ----
Type: Caught ACCESS_VIOLATION (DEP at 0000000000000000)
Message: Caught an exception.
Stack Trace:
  0000000000000000
  00007FF61AC74355 (GTA5.exe+0000000000444355, 00007FF7B6C94355)
  00007FFCC51E6A26 (Stand 24.7.8, 13376942006C6A26)
  00007FFCC51A599F (Stand 24.7.8, 133769420068599F)
  00007FFCC5254C3F (Stand 24.7.8, 1337694200734C3F)
  00007FFCC5254A4C (Stand 24.7.8, 1337694200734A4C)
  00007FFCC5254A5C (Stand 24.7.8, 1337694200734A5C)
  00007FFD6B18A521 (KERNELBASE.dll+000000000007A521): RegQueryInfoKeyA
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[7/28/2024 2:25:01 PM] ---- ERROR INFORMATION ENDS ----
[7/28/2024 2:25:02 PM] ---- ERROR INFORMATION BEGINS ----
Type: Caught ACCESS_VIOLATION while reading from FFFFFFFFFFFFFFFF
Message: Caught an exception.
Stack Trace:
  00007FF61AC7434F (GTA5.exe+000000000044434F, 00007FF7B6C9434F)
  00007FFCC51E6A26 (Stand 24.7.8, 13376942006C6A26)
  00007FFCC51A599F (Stand 24.7.8, 133769420068599F)
  00007FFCC5254C3F (Stand 24.7.8, 1337694200734C3F)
  00007FFCC5254A4C (Stand 24.7.8, 1337694200734A4C)
  00007FFCC5254A5C (Stand 24.7.8, 1337694200734A5C)
  00007FFD6B18A521 (KERNELBASE.dll+000000000007A521): RegQueryInfoKeyA
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[7/28/2024 2:25:02 PM] ---- ERROR INFORMATION ENDS ----
[7/28/2024 2:25:02 PM] ---- ERROR INFORMATION BEGINS ----
Type: Caught ACCESS_VIOLATION (DEP at 0000000000000000)
Message: Caught an exception.
Stack Trace:
  0000000000000000
  00007FF61AC74355 (GTA5.exe+0000000000444355, 00007FF7B6C94355)
  00007FFCC51E6A26 (Stand 24.7.8, 13376942006C6A26)
  00007FFCC51A599F (Stand 24.7.8, 133769420068599F)
  00007FFCC5254C3F (Stand 24.7.8, 1337694200734C3F)
  00007FFCC5254A4C (Stand 24.7.8, 1337694200734A4C)
  00007FFCC5254A5C (Stand 24.7.8, 1337694200734A5C)
  00007FFD6B18A521 (KERNELBASE.dll+000000000007A521): RegQueryInfoKeyA
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFD6D75091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[7/28/2024 2:25:02 PM] ---- ERROR INFORMATION ENDS ----

i believe these are all the same 

note that it also happens on default

**Comment by Sainan** [comment]
Don't spam it, then.
