### ISSUE TITLE
Wrong HEX

### ISSUE THREAD

**Issue by standggreport** [calamity-inc/Stand-Feedback#257]
- **Pproblem description**
  - When entering HEX 800080 or 80008000, it is incorrectly interpreted as 127, 0, 127 (#7f007f) instead of 128, 0, 128 (#800080).
- **Steps to reproduce**
  1. Find any place where you can apply a HEX color code.
  2. Enter #80008000 or #800080.
  3. Observe that the color is incorrectly applied as 127, 0, 127 (#7f007f).
  4. Enter the same HEX code a second time.
  5. Observe that the color is correctly applied as 128, 0, 128 (#800080).
- **Sufficient context**
  - This issue occurs when entering specific HEX color codes.
  - Reproducing the issue shows an initial incorrect interpretation followed by correct behavior on the second attempt.
Video: https://youtu.be/eF2G766YknU
![image](https://github.com/user-attachments/assets/9071484d-40fa-40e7-aee0-263026b8feb0)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
