### ISSUE TITLE
timestamp in messages sending duplicate message

### ISSUE THREAD

**Issue by zfdfgffretherrfw** [calamity-inc/Stand-Feedback#258]
Online \ Chat \ Timestamp In Messages

pressing key quick after sending message sends same message with key pressed at end

![Screenshot_1208](https://github.com/user-attachments/assets/f4ead39c-4208-4405-a0a2-e179011266c8)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
