### ISSUE TITLE
Unable to close the game normally

### ISSUE THREAD

**Issue by latiao-1337** [calamity-inc/Stand-Feedback#26]
- **Explicit description of the problem**
The process persists after the game is closed (must be closed manually, otherwise the game process will always exist and cannot be started again)
- **Steps to reproduce**
Close the game
- **Sufficient context**
Not using ASI/LUA
Default configuration
If you open the console, it will appear after exiting
![图片](https://github.com/calamity-inc/Stand-Feedback/assets/146958060/4363f01d-f64c-48fb-95f8-30346bb37f0e)

System language zh_cn

stand Profiles
[none.txt](https://github.com/user-attachments/files/15740231/none.txt)

log.txt

[Log.txt](https://github.com/user-attachments/files/15740247/Log.txt)

**Comment by Sainan** [comment]
It does look like there is a third-party integration hooking into the game (and logging to the console).
