### ISSUE TITLE
GeoIP is not showing, its just blank

### ISSUE THREAD

**Issue by sytcal** [calamity-inc/Stand-Feedback#261]
![image_2024-08-01_171305814](https://github.com/user-attachments/assets/2ff660a0-f736-42a9-bdb4-392f35c4371f)

**Comment by AssemblyLangFTW** [comment]
Are they connected via a relay? If they are you can't see GeoIP stuff

**Comment by sytcal** [comment]
> Are they connected via a relay? If they are you can't see GeoIP stuff

no ones geoip is showing
