### ISSUE TITLE
Tabs Positioning Bug

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#263]
I found a small and very minor bug when playing around with tabs positioning, the video will speak for me.

https://github.com/user-attachments/assets/10452454-dc4a-4af8-ae2c-8bf190107d22

**Comment by Sainan** [comment]
What is the expected behaviour? You made the tabs smaller than the list so the grid engine decided that's the best place to put it.

**Comment by isytrana** [comment]
i expected the tabs to do like at the top and just getting smaller, not moving switching to the opposite side.
