### ISSUE TITLE
Installing some Dependencies doesnt seem to work.

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#264]
I tried to install the "Soup" dependency as its the only one I didnt have, and it fails to download stuff
![image](https://github.com/user-attachments/assets/1127aa1a-6226-4a12-85ad-426dcbac3d18)

~~Apparently doesn't work for natives aswell, which I didnt try, I'll try it if I find how.~~
Every dependencies except Soup works.

**Comment by Sainan** [comment]
This report belongs on https://github.com/calamity-inc/Stand-Repository, but I will be working getting these files migrated.
