### ISSUE TITLE
Analog Support

### ISSUE THREAD

**Issue by phnx119** [calamity-inc/Stand-Feedback#266]
I have a Wooting Two HE and when I turn on **analog support** in stand, I can **no longer open the player list** with "Y". I can still use Y everywhere else e.g. in chat. When I turn off analog support I can open the player list with Y again. All other keys work as intended.

**Comment by Sainan** [comment]
Hmm, I suppose you have a QWERTZ layout in Windows. Does it work when you press Z & Y at the same time?

**Comment by Sainan** [comment]
Will be fixed in the next update.

**Comment by phnx119** [comment]
Pressing Z & Y at the same time works. I also noticed that I also cant open team chat with T

**Comment by Sainan** [comment]
I assume you mean "open team chat with Z"? Either way, it should also be fixed in the next update as Stand was not handling the QWERTZ layout correctly.

**Comment by phnx119** [comment]
Yes I meant Z. When i press Y and Z at the same time it opens the playerlist and sometimes also teamchat at the same time
