### ISSUE TITLE
Wrong applying color

### ISSUE THREAD

**Issue by standggreport** [calamity-inc/Stand-Feedback#267]
- **Problem description**
  - When spawning any vehicle, then entering LSC and painting everything white (not via HEX), and then spawning a new vehicle, pressing U, then the up arrow, and replaying the previous command (vehprimarygreen 255 / vehprimaryred 255 / vehprimaryblue 255), the entire vehicle turns white instead of only changing the RGB values.
- **Steps to reproduce**
  1. Spawn any vehicle.
  2. Enter LSC and paint everything white (in 255) (not using HEX).
  3. Spawn a new vehicle.
  4. Press U, then the up arrow to replay the previous command (vehprimarygreen 255 / vehprimaryred 255 / vehprimaryblue 255).
  5. Observe that the entire vehicle turns white instead of only changing the RGB values.

Its possible without Color Spawned Vehicle and possible with spawning different cars
Video: https://youtu.be/35bYrOs8O9E + https://youtu.be/VpTIK0-UCwU

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
