### ISSUE TITLE
Field Of View Issue

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#268]
When using the Marksman Rifle Mk II (With Holographic Sight) or the Precision Rifle, my edit for "Aiming" doesn't apply and instead applies the one to "Sniping", which is unmodified.

**Comment by Sainan** [comment]
I don't see the problem. You're sniping, so it's using your "sniping" configuration.

**Comment by isytrana** [comment]
The issue here is the fact that the Precision Rifle doesn't have a proper sniping scope nor does my Marksman Rifle, they should take the aiming configuration and not the sniping one.

**Comment by Sainan** [comment]
The game considers these to be sniper rifles, so they are considered sniping, not aiming.
