### ISSUE TITLE
Labels: removelabel / resetlabel

### ISSUE THREAD

**Issue by standggreport** [calamity-inc/Stand-Feedback#269]
**Is your feature request related to a problem? Please describe.**
In the stand, there is addlabel and editlabel, but there is no removelabel or resetlabel. Why? 

**Describe the solution you'd like**
With removelabel or resetlabel, you can quickly return what you need to its original place without searching for it in the menu or entering the menu. Just erase it with one command.

**Describe alternatives you've considered**
I've considered manually finding and removing labels through the menu, but this is more time-consuming and less efficient.

**Additional context**
Adding removelabel or resetlabel would greatly simplify working with labels.

**Comment by Sainan** [comment]
Will add command names for these actions in the next update.
