### ISSUE TITLE
Dns issue with 115.9

### ISSUE THREAD

**Issue by SlideWaysCam** [calamity-inc/Stand-Feedback#27]
Since the 115.9 update came out i have not been able to paste my activation key, when  i  load into single player it shows the stand ultimate menu but with the activation tab still on the top. If and when i go to put the activation key in it says validating key and never does. It then says “stand caught an exception, find the error info in the log.txt” so i go into my logs and it says “failed to send a request to stand.gg: DNS query yeiled no results. I have also tried 115.8 and it does the same. I had to go back to 115.7 to get it to work

**Comment by Sainan** [comment]
Could you share your Log.txt?

**Comment by SlideWaysCam** [comment]
Executing Script: MainTransition
  Executing Operation: Native 0x0888C3502DBBEEF5
[6/7/2024 1:34:50 PM] ---- ERROR INFORMATION ENDS ----
[6/7/2024 1:34:51 PM] Failed to send a request to stand.gg: DNS Query Yielded No Results

**Comment by SlideWaysCam** [comment]
> Could you share your Log.txt?

Executing Script: MainTransition
  Executing Operation: Native 0x0888C3502DBBEEF5
[6/7/2024 1:34:50 PM] ---- ERROR INFORMATION ENDS ----
[6/7/2024 1:34:51 PM] Failed to send a request to stand.gg: DNS Query Yielded No Results

**Comment by Sainan** [comment]
Add `DNS Conduit: OS` to your Meta State.txt as a workaround for now

**Comment by SlideWaysCam** [comment]
> Add `DNS Conduit: OS` to your Meta State.txt as a workaround for now

I changed it to that and i tried smart as well neither worked, only thing that seems to work was rolling back to 115.7

**Comment by Sainan** [comment]
Could you use __Stand > Experiments > Run Network Diagnostics__ and then share the result from your Log.txt?

**Comment by SlideWaysCam** [comment]
> Could you use **Stand > Experiments > Run Network Diagnostics** and then share the result from your Log.txt?

+ repeated 14 times
[6/17/2024 11:45:31 AM] ---- START OF NETWORK DIAGNOSTICS ----
Could not find a DHCP server on the network. Probably a VPN.
DNS on UDP with 1.1.1.1:
- Asking for an IPv4: Did not get a reply.
- Asking for an IPv6: Did not get a reply.
DNS on HTTPS (DoH) with 1.1.1.1:
- Asking for an IPv4: Did not get a reply.
- Asking for an IPv6: Did not get a reply.
[6/17/2024 11:45:31 AM] ---- END OF NETWORK DIAGNOSTICS ----
[6/17/2024 11:45:35 AM] Failed to send a request to stand.gg: DNS Query Yielded No Results

**Comment by SlideWaysCam** [comment]
i dont even use a vpn tho
