### ISSUE TITLE
Stand Labels

### ISSUE THREAD

**Issue by standggreport** [calamity-inc/Stand-Feedback#270]
- **Problem description**
  - When using Lua to modify vehicle labels, it works fine, but when trying to modify weapon labels, it doesn’t work. This is because Stand doesn’t remove the underscore and attempts to edit the label 'WT_GL' instead of 'WTGL'. The label should be processed without the underscore to work correctly, as manual editing works fine because the underscore is removed.
- **Steps to reproduce**
  1. Create a Lua script to modify vehicle labels and observe that it works correctly.
  2. Modify the Lua script to change weapon labels.
  3. Notice that the label 'WT_GL' is not edited correctly.
  4. Manually edit the label (it editing without _)
  5. Observe that the label changes correctly because the underscore is removed.
- **Sufficient context**
  - This issue arises from how Stand handles underscores in labels.
  - Manual editing confirms that removing the underscore allows the label to be modified as expected.
  
  Video: https://youtu.be/T3Drq9wHDRs

**Comment by Sainan** [comment]
This seems to be an issue with your Lua script.

**Comment by standggreport** [comment]
> This seems to be an issue with your Lua script.

But why stand cant edit this one? If i can edit this manually?
