### ISSUE TITLE
Bad translation in Russian

### ISSUE THREAD

**Issue by Lirniri** [calamity-inc/Stand-Feedback#272]
![image](https://github.com/user-attachments/assets/14a7d3d9-5905-4b66-8287-cefd8da19f66)

In Russian it is written: Walking and swimming speed

Although the name of command specifies that only walking

**Comment by 99Anvar99** [comment]
Спасибо что указали на это. Будет исправлено в ближайшем времени

**Comment by Lirniri** [comment]
> Спасибо что указали на это. Будет исправлено в ближайшем времени

Вот ещё что нужно поправить
![GTA5_QJJupDk7MU](https://github.com/user-attachments/assets/d0792b51-d041-4b67-b49a-a360740acf21)

**Comment by 99Anvar99** [comment]
> > Спасибо что указали на это. Будет исправлено в ближайшем времени
> 
> Вот ещё что нужно поправить ![GTA5_QJJupDk7MU](https://private-user-images.githubusercontent.com/106456219/356260928-d0792b51-d041-4b67-b49a-a360740acf21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzM4NDEsIm5iZiI6MTcyMzEzMzU0MSwicGF0aCI6Ii8xMDY0NTYyMTkvMzU2MjYwOTI4LWQwNzkyYjUxLWQwNDEtNGI2Ny1iNDlhLWEzNjA3NDBhY2YyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQxNjEyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTc3MWU5ZGMwYjAwZWVhY2Y5ZGY4OGEyMGZkMjUyYzcwYTBjMDYxZDQ4NmYzYTY4ZDk0ZDBiNjk2YjUzZDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.br375TFGCpjpt-Gf2oMPg2_Ee7OiAZPJaA8u1bZ4WIg)

Понял, спасибо что указал. Если найдешь еще, не стесняйся, сообщай.

**Comment by Lirniri** [comment]
![GTA5_8ypU6tpc96](https://github.com/user-attachments/assets/383fb2a7-5bdd-4ef2-a872-0cd545e76ee9)
Знак вопроса вместо мягкого знака ( Ь )

**Comment by Sainan** [comment]
That appears to be a font issue, unrelated to the Russian translation. I'll take care of that.
