### ISSUE TITLE
New feature: remove label

### ISSUE THREAD

**Issue by standggreport** [calamity-inc/Stand-Feedback#273]
**Problem description**
- After the update that introduces label removal functionality, an issue occurs when using the `addlabel` command with similar labels. If you first add a label for `caddy3` and then add a label for `caddy` (or vice versa), and later use the `removelabel caddy` command twice, both `caddy` and `caddy3` are removed, even though `caddy3` should not be deleted.

**Steps to reproduce**
1. Use the `addlabel` command to add the label `caddy3`.
2. Use the `addlabel` command again to add the label `caddy`.
3. Run the `remove caddy` command.
4. Run the `remove caddy` command again.
5. Observe that both `caddy` and `caddy3` labels are removed, even though `caddy3` should remain.

**Sufficient context**
- The issue is caused by how the removal process handles labels with similar names. When `remove caddy` is executed twice, it incorrectly removes `caddy3` along with `caddy`, even though only `caddy` should be removed.

**VIDEO: https://youtu.be/xfQ_ibwufsY**

**Comment by Sainan** [comment]
Intendended functionality, see "automatic completion" at https://stand.sh/help/command-box-documentation
