### ISSUE TITLE
Session Browser: Add Filter Ad Bots

### ISSUE THREAD

**Issue by isdzjfs** [calamity-inc/Stand-Feedback#274]
**Is your feature request related to a problem? Please describe.**
In Hong Kong sessions, most of the sessions are hosted by an ad bot, they block all sync and you can't even kick or crash them

**Describe the solution you'd like**
Add an option to the session browser to filter sessions that are hosted by adbots

**Describe alternatives you've considered**

**Additional context**

**Comment by Sainan** [comment]
We'll add a filter for sessions hosted by known advertisers.
