### ISSUE TITLE
disable chat command reply (please)

### ISSUE THREAD

**Issue by Sano-kz** [calamity-inc/Stand-Feedback#276]
It is actually possible to set the reply visibility to 'Everyone', 'Issuer & Me', or 'Issuer'. However, to be more discreet, it would be useful to disable the reply option.

**Comment by Sainan** [comment]
I don't understand. If you enabled chat commands for someone, and they know you have, and they are using the chat commands, what discreteness is there left to lose?

**Comment by Sano-kz** [comment]
> I don't understand. If you enabled chat commands for someone, and they know you have, and they are using the chat commands, what discreteness is there left to lose?

To use it "anonymously", everyone can use the commands but no one knows who is the modder

**Comment by Sainan** [comment]
Okay, we'll add some more options for it.
