### ISSUE TITLE
Console Suggestions

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#278]
In my opinion, Stand's console is not as stylish as the menu itself, so here's two suggestions to make it better:
- Having the ability to change the ASCII art's font of Stand / Removing it
- Having the ability to have a general color for the whole console or having color codes so that a specified event has a specified color in the console.

**Comment by Sainan** [comment]
You mean the windows console? The one with all of these customisation options?

![image](https://github.com/user-attachments/assets/7c3d071f-e154-48a3-9d9c-fab5a12a2bf8)

**Comment by isytrana** [comment]
And why not having an easier access to that by having those directly in the menu huh? Not everyone knows how to access it.
Plus you can't code via color different events nor remove the ascii art.
L "solution".

**Comment by Sainan** [comment]
I understand your desire for more colour in the logging, but the console is basically just an ephermal view of the Log.txt, and a text file can't contain colour.

**Comment by isytrana** [comment]
But why not making that ephermal view of the Log.txt better to look at? :(
