### ISSUE TITLE
Kick P1 Auto-Kicks for some reason.

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#279]
It seems like whatever reaction you have, the P1 automatically kicks the kicker for no reason.
![image](https://github.com/user-attachments/assets/76dac65c-c937-44b3-954d-c7911c64ec20)
![image](https://github.com/user-attachments/assets/d63ce648-287f-4a56-9429-b3537db9ab24)

**Comment by isytrana** [comment]
Also my friend is not Co-Loading, the false Co-Loading issue is still here.

**Comment by Sainan** [comment]
Attempting to kick the host can have such effects, this is not a bug.
