### ISSUE TITLE
error on inject

### ISSUE THREAD

**Issue by NickB926** [calamity-inc/Stand-Feedback#28]
A good issue report has _at least one_ of these:
- **Obvious problem description**
  - For example: "I expected Immortality to make me immortal, but I still died."
- **Steps to reproduce**
- **Sufficient context**
  - For things related to detections, the things in the parentheses.
  - For false-positives, a log of the event.
  - Stack trace, if applicable, and if Stand's DLL is a major part of it.
  
  Action: Continuing execution at a ret instruction because the current instruction is inaccessible.
[6/7/2024 10:58:09 PM] ---- ERROR INFORMATION ENDS ----
[6/7/2024 11:00:31 PM] Stand 115.9 reporting for duty!
[6/7/2024 11:00:31 PM] Scanned Stealy V-eely Automobiley 1.68-3179 for 258 sigs in 6.09227 ms (258 from cache)
[6/7/2024 11:00:32 PM] Did main hooks in 654.07666 ms.
[6/7/2024 11:00:33 PM] Got additional sigs from auth, scanned in 13.04404 ms.
[6/7/2024 11:00:33 PM] ---- ERROR INFORMATION BEGINS ----
Type: Caught ACCESS_VIOLATION while reading from 0000000000000028
Message: Caught an exception.
Stack Trace:
  00007FFF8676623B (Stand 115.9, 133769420073623B)
  00007FFF865CFBE8 (Stand 115.9, 133769420059FBE8)
  00007FFF86457209 (Stand 115.9, 1337694200427209)
  00007FFF866FD839 (Stand 115.9, 13376942006CD839)
  00007FFF866FD9AA (Stand 115.9, 13376942006CD9AA)
  00007FFF866FD9AA (Stand 115.9, 13376942006CD9AA)
  00007FFF866FD9AA (Stand 115.9, 13376942006CD9AA)
  00007FFF8678E7B0 (Stand 115.9, 133769420075E7B0)
  00007FFF86701EC4 (Stand 115.9, 13376942006D1EC4)
  00007FFF866E4B9F (Stand 115.9, 13376942006B4B9F)
  00007FFF8679430F (Stand 115.9, 133769420076430F)
  00007FFF8679411C (Stand 115.9, 133769420076411C)
  00007FFF8679412C (Stand 115.9, 133769420076412C)
  00007FF824FDC101 (KERNELBASE.dll+000000000007C101): PackageIdFromFullName
  00007FF82774FFEA (ntdll.dll+000000000007FFEA): RtlUserFiberStart
  00007FF82774FFEA (ntdll.dll+000000000007FFEA): RtlUserFiberStart
[6/7/2024 11:00:34 PM] ---- ERROR INFORMATION ENDS ----

**Comment by Sainan** [comment]
This stacktrace seems completely busted; it does not match up with 115.9 at all. Try deleting your Bin folder. Otherwise, steps to reproduce will be needed.
