### ISSUE TITLE
Online > Session > Clear Blacklist | Does not work

### ISSUE THREAD

**Issue by IlIlIlIIlIlIlIl** [calamity-inc/Stand-Feedback#284]
> Online > Session > Clear Blacklist

 This feature does nothing ↑
- **Steps to reproduce**
   - Host kick a player
   - Clear Blacklist
   - They still can't join back
![image](https://github.com/user-attachments/assets/70b193ee-ac33-4f03-9d3c-e98b69b3fa9c)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
