### ISSUE TITLE
Faster cursor scrolling.

### ISSUE THREAD

**Issue by UnionProject** [calamity-inc/Stand-Feedback#285]
After using some other mod menus, I noticed that the cursor scrolling speed is significantly faster in them.
And the "acceleration" phase starts in much quicker than in Stand.

My suggestion is to add the **ability to change or just increase the cursor scrolling speed** and place it next to the "Smooth Scrolling" option in the settings.
As an alternative, I can only suggest changing the time it takes for the cursor to increase speed. Currently, it's around 3 seconds, but it would be much nicer if faster scrolling started after 1-2 seconds of continuous scrolling.

This would greatly improve the convenience and speed of using Stand.

**Comment by Sainan** [comment]
You can try lowering these settings:
- Stand > Settings > Input > Key Repeat Interval
- Stand > Settings > Input > Key Long-Hold Repeat Interval
