### ISSUE TITLE
vehicle indestructible causing some vehicles to freak out

### ISSUE THREAD

**Issue by deathking61** [calamity-inc/Stand-Feedback#290]
A good issue report has _at least one_ of these:
- using the indestructible vehicle option 
  - For example: i expected it to make my car not die but while doing that it causes the nero custom and some others to full on spasm out till toggled off

1. launch game and then stand 
2. open stand go to the vehicles tab 
3. enable "indestructible" 
4. drive something like the nero custom 

if you need anything else let me know and ill try to get it

**Comment by deathking61** [comment]
ok so upon more testing doing it this way instead: Players > yourname > Friendly > Vehicle > Indestructible this way doesn't cause the same issues

**Comment by isytrana** [comment]
This will be fixed next update, Xenorhase already reported it :)

**Comment by deathking61** [comment]
when is the next update?

**Comment by deathking61** [comment]
may i ask what caused this issue? i find knowing some things like why something happens is kinda neat
