### ISSUE TITLE
Speed limit not working for all cars

### ISSUE THREAD

**Issue by phnx119** [calamity-inc/Stand-Feedback#292]
The speed limit option in movement does not work for all cars. 
The cars i noticed it doesnt work with (*speed limit*):
Neon (188kph), comet s2 (209), cypher (198), entity xxr(216), growler (216), khamelion (170), tyrant (216), tezeract (206).
I tried almost every option in handling to change the limit but the only way to go faster is with superdrive.
Gravitym and vhac cant change it either.
Engine power multiplier increases the limit but not by a lot. For example power mult of 5 and gravitym of 5 increases the speed limit on the Neon to 285 (from 188kph), traction and acceleration suffers from it tho.

**Comment by Sainan** [comment]
Speed limit works as intended.

**Comment by phnx119** [comment]
Is it intended to not overwrite the limit of the car? Because when I set it lower than the cars limit it works, but not when I go above that

**Comment by Sainan** [comment]
It changes the maximum speed that the vehicle can possibly be moving at. If you actually manage to move that fast is not its concern.
