### ISSUE TITLE
SOCD

### ISSUE THREAD

**Issue by phnx119** [calamity-inc/Stand-Feedback#293]
Is it possible to add compatibility for wootings SOCD? Currently it takes the raw input both with analog support on and off.

**Comment by Sainan** [comment]
With analogue support off, Wooting's firmware-level SOCD resolution algorithms should work ensure only non-opposing inputs are reported for the digital input.

For analogue input, SOCD is not a problem because your intended input is always clear from the analogue values (furthest down wins, similar to "Rappy Snappy" for digital input.)

**Comment by phnx119** [comment]
For me it doesnt work. With SOCD enabled, when I hold A and then press D it should only do the D input but instead it does both, canceling each other out. No other inputs and doesnt matter if analogue support is on or off. Instead it works like Rappy Snappy as you said. So is SOCD not possible?

**Comment by Sainan** [comment]
This might be an issue with your keyboard. It's not related to Stand.

**Comment by phnx119** [comment]
It works as intented everywhere else

**Comment by Sainan** [comment]
Then unload Stand and see if the issue persists.

**Comment by phnx119** [comment]
Only happens when stand is loaded.

**Comment by Sainan** [comment]
Rappy Snappy seems to work fine when Analogue Keyboard Support is disabled in Stand.

**Comment by phnx119** [comment]
Yes Rappy Snappy works fine, but not SOCD

**Comment by Sainan** [comment]
With analogue keyboard support **disabled**?

**Comment by phnx119** [comment]
Also doesnt work when its disabled

**Comment by Sainan** [comment]
SOCD: Last Input Priority also works fine for me with analogue keyboard support disabled. Obviously analogue keyboard support means your input is independent of such digital input considerations.

**Comment by phnx119** [comment]
Ah ok that explains it
