### ISSUE TITLE
There is some error in the logic when executing the Lua script

### ISSUE THREAD

**Issue by Lirniri** [calamity-inc/Stand-Feedback#296]
[12.08.2024 2:42:38] ---- НАЧАЛО ИНФОРМАЦИИ ОБ ОШИБКЕ ----
Type: Caught ACCESS_VIOLATION while reading from 0000000000000002
Message: Произошла какая-то ошибка
Примечание: Эта ошибка возникла при выполнении Lua скрипт.
Stack Trace:
  00007FFB4951AA96 (Stand 24.8.5, 133769420053AA96)
  00007FFB494FB2C2 (Stand 24.8.5, 133769420051B2C2): util.get_tunable_bool
  00007FFB4977F68A (Stand 24.8.5, 133769420079F68A)
  00007FFB4977F9FB (Stand 24.8.5, 133769420079F9FB)
  00007FFB4977A3D8 (Stand 24.8.5, 133769420079A3D8)
  00007FFB4977FD92 (Stand 24.8.5, 133769420079FD92)
  00007FFB4977E9B3 (Stand 24.8.5, 133769420079E9B3)
  00007FFB497801EA (Stand 24.8.5, 13376942007A01EA)
  00007FFB497C290B (Stand 24.8.5, 13376942007E290B)
  00007FFB497C2A71 (Stand 24.8.5, 13376942007E2A71)
  00007FFB4977F68A (Stand 24.8.5, 133769420079F68A)
  00007FFB4977F9FB (Stand 24.8.5, 133769420079F9FB)
  00007FFB4977A3D8 (Stand 24.8.5, 133769420079A3D8)
  00007FFB4977FAE6 (Stand 24.8.5, 133769420079FAE6)
  00007FFB4977E9B3 (Stand 24.8.5, 133769420079E9B3)
  00007FFB49753FCE (Stand 24.8.5, 1337694200773FCE)
  00007FFB4978E033 (Stand 24.8.5, 13376942007AE033)
  00007FFB4977F68A (Stand 24.8.5, 133769420079F68A)
  00007FFB4977AB0C (Stand 24.8.5, 133769420079AB0C)
  00007FFB4977FAE6 (Stand 24.8.5, 133769420079FAE6)
  00007FFB49753E64 (Stand 24.8.5, 1337694200773E64)
  00007FFB494CA9EE (Stand 24.8.5, 13376942004EA9EE)
  00007FFB4967100F (Stand 24.8.5, 133769420069100F)
  00007FFB4971FCBF (Stand 24.8.5, 133769420073FCBF)
  00007FFB4971FACC (Stand 24.8.5, 133769420073FACC)
  00007FFB4971FADC (Stand 24.8.5, 133769420073FADC)
  00007FFBFB86A521 (KERNELBASE.dll+000000000007A521): RegQueryInfoKeyA
  00007FFBFDE9091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFBFDE9091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[12.08.2024 2:42:38] ---- КОНЕЦ ИНФОРМАЦИИ ОБ ОШИБКЕ ----

**Comment by Sainan** [comment]
Steps to reproduce?

**Comment by Sainan** [comment]
Since this error occured while executing user-generated content, you should contact the responsible developer. This issue tracker is for issues with Stand itself, not user-generated content for Stand.

**Comment by Lirniri** [comment]
Okay, I'm contacting the developer. Only if I'm the developer myself xD
