### ISSUE TITLE
Kick Event (S3) when joining a organization and calling out any associate vehicle

### ISSUE THREAD

**Issue by Zaptize** [calamity-inc/Stand-Feedback#299]
It isn't a super big bug but it has been around for quite some time (I never made a guilded post because guilded sucks ass), but I came across it again yesterday, if I try calling out something like a CEO Buzzard, it will cause the CEO (if modding) to get a kick event from me.

**Comment by Sainan** [comment]
Do you have a log of this event?

**Comment by Zaptize** [comment]
[11.08.2024 22:54:46] Kick Event (S3) from VeryFloofyBoi: Script Event: {0: -1140090124, 1: 26, 2: 2048, 3: 788747387, 4: 0}
+ repeated 3 times

This is the only thing in there for it

**Comment by Sainan** [comment]
Thanks. Will be fixed in the next update.
