### ISSUE TITLE
Invulnerability tag on players during Humane Labs Raid Heist

### ISSUE THREAD

**Issue by nuggettowin** [calamity-inc/Stand-Feedback#3]
When I host the Humane Labs Raid apartment heist, all other players are marked as invulnerable/attacking while invulnerable throughout the entire heist even though they are not (they do actually take damage and die). When I die during the heist, I also get marked as invulnerable once I respawn even if I'm not. 

Doesn't occur on the other apartment heists and casino heist.

**Comment by Sainan** [comment]
Works as intended.
