### ISSUE TITLE
Horn boost needs less jank

### ISSUE THREAD

**Issue by StreetSurfer1** [calamity-inc/Stand-Feedback#302]
I'm always frustrated when I use stand's horn boost because it's so overpowered and not able to be fine tuned. Menyoo horn boost is very smooth.  With menyoo I can gracefully control the bmx with horn boost. Not so with stand horn boost.

ability to fine tune horn boost, or a horn boost that replicates menyoo.

**Comment by Sainan** [comment]
Stand doesn't have a "horn boost". There's a Super Drive, and you can lower the "Speed" value as much as you desire.
