### ISSUE TITLE
Please make Stand icon more rounded

### ISSUE THREAD

**Issue by tumkas** [calamity-inc/Stand-Feedback#303]
![image](https://github.com/user-attachments/assets/390701a1-d87c-4c35-a31d-a0a38743782c)

Would be best if you also change color to pastel pink to make it smoother.

Thanks for your attention.

**Comment by IlIlIlIIlIlIlIl** [comment]
💀

**Comment by Lirniri** [comment]
I think it would be better to have the ability to customize the stand icon etc.

**Comment by isytrana** [comment]
You can change it yourself by creating a Shortcut to Stand Launchpad and change the icon of it, it'll change the icon in the taskbar.
![image](https://github.com/user-attachments/assets/b3dd0a9f-62b5-48f3-a2c6-d599840a08d2)

**Comment by Sainan** [comment]
It somewhat depends on what apps you use. For example, I use VoiceMeeter, Sublime Text, and Sublime Merge every day, and they all have perfectly square icons, so Stand's not too peculiar in that regard. Sure, the pure magenta may be a bit extreme, but that's just our brand at this point.

We also don't plan to do any branding changes. Furthermore, we don't have any designers in-house (could you tell?) who would be able to do this "properly."

I'd advise you to do what @ScriptHost suggested, if it really bothers you that much.
