### ISSUE TITLE
Sound notification when pressing keybinds

### ISSUE THREAD

**Issue by UnionProject** [calamity-inc/Stand-Feedback#305]
Im using stand mostly with keysbinds, I have absolutely everything I need on the keyboard, but there is a problem, every time I press a key to enable or disable a function, I see this stand notification that says the function is enabled or disabled. But when I press a lot of keys in a row on the screen creates a lot of notifications, it looks ugly imo and just clutters and becomes difficult to navigate. I've disabled these notifications, but without them it's hard to know if I've turned the function on or off.

My soulution is to add small and simple notification sound, either just for keybinds or for every turn on/off option in menu itself.
Make it possible to disable it in settings or configure volume of sound or change then it self by dropping another file in stand folder.

1. Sound for toggle options
2. Error Sounds (if you type mistake in command box and press enter or some critical errors)
3. Sounds for simple options, which is not toggling options, like "sync time" in stand menu

Example of sounds:
https://github.com/user-attachments/assets/173e2051-f692-4b76-a45f-a0cfbadeb3bf
Just used random windows sounds, but in my opinion they should be shorter, and a bit more unnoticeble, just a little.

**Comment by Sainan** [comment]
It's funny you say this because there already are sound effects, and they're supposed to work for hotkeys, but I guess that part is broken.

**Comment by Sainan** [comment]
Will be fixed in the next update.
