### ISSUE TITLE
More options to vehicle collision

### ISSUE THREAD

**Issue by AndreasPB0** [calamity-inc/Stand-Feedback#307]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the option to disable collisions with peds, props and walls. So that you can pretty much drive through anything, other than the ground.

**Describe alternatives you've considered**
Other menus. Almost every other menu has this option and i dont see why stand shouldnt have it.

**Additional context**
This could probably be made easily with LUA but i dont have the knowledge to do it.

**Comment by awaseru** [comment]
we'll be adding this for peds and props. behind many walls there is no ground, so you would fall through the map without them.
