### ISSUE TITLE
Bug with Fix Vehicle function or with IS_ENTITY_DEAD Native in Story Mode

### ISSUE THREAD

**Issue by Lirniri** [calamity-inc/Stand-Feedback#313]
- **Obvious problem description**
  - In story mode, if you blow it up in any way, and then restore it, then when you try to blow it up through the Watch Dogs Like World Hacking function, it will not explode
(Most likely there is a problem with the native IS_ENTITY_DEAD in story mode, but this is not certain.)
- **Steps to reproduce**
- Blow up the car in any way. 
After that, call the function of Fix Vehicle.
Try to blow up a car using Watch Dogs Like World Hacking
Done, you won't be able to blow up the car again

**Comment by Sainan** [comment]
Thanks for the report. Will be fixed in the next update.

**Comment by Lirniri** [comment]
> Thanks for the report. Will be fixed in the next update.

How did you fix this error, what natives should I use to fix this error?
