### ISSUE TITLE
Entity Previews: Add setting entity alpha value

### ISSUE THREAD

**Issue by isdzjfs** [calamity-inc/Stand-Feedback#317]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add an option to set the transparency when previewing entities instead of always being semi-transparent

**Describe alternatives you've considered**

**Additional context**

**Comment by Sainan** [comment]
We'll add an option to make entity previews opaque in the next feature update (likely sometime next month).
