### ISSUE TITLE
players being false flagged as modder and self tag being applied to others

### ISSUE THREAD

**Issue by owleague** [calamity-inc/Stand-Feedback#318]
playing a freemode lobby with a few friends and random players keep getting marked as "stand user" and "presence spoofing" then are applied the "self" tag
Steps to reproduce: N/A Randomly occurs while playing normally in a lobby
![image](https://github.com/user-attachments/assets/36eddad5-f1dc-4b74-96a8-ad63b255f3e6)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
