### ISSUE TITLE
Weapon function suggestions

### ISSUE THREAD

**Issue by chen02016** [calamity-inc/Stand-Feedback#321]
Requested feature :
Full vehicle weapon handling editor.
LIKE vehicle movement handling editor.
With SUB handling.
like HomingRocketParams
TurnRateModifier value
PitchYawRollClamp value

and add like deluxo will not lose target.tracking ability
and add explosion replacement like RAIJU cannon explosion replaced with STICKYBOMB

**Comment by Sainan** [comment]
One suggestion per ticket, please.

**Comment by chen02016** [comment]
Hello, my suggestion is to provide the vehicle weapon locking option and add the vehicle missile 100% hit target function
Please forgive my ignorance, why was I removed from the Stand community? Please forgive me this time, I did not intentionally violate the rules. Stand is the best menu I have ever used, and the Stand community is very important to me. Please forgive me for allowing me to join the community. Thank you



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 23, 2024 03:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [calamity-inc/Stand-Feedback] Weapon function suggestions (Issue#321)




 
One suggestion per ticket, please.
