### ISSUE TITLE
Hosttoken spoofing cant be disabled

### ISSUE THREAD

**Issue by Cetendo** [calamity-inc/Stand-Feedback#323]
Hosttoken spoofing cant be disabled:
- **If you turn hosttoken spoofing off and join a new lobby the token is still getting spoofed**
- 
- **Steps to reproduce**
  - Turn hosttoken spoofing on
  - join a new lobby
  - turn hosttoken spoofing off
  - join a new lobby 
  and the hosttoken is still spoofed

**Comment by Sainan** [comment]
I am unable to reproduce this with the steps provided. However, it is possible that your original host token is no longer known after unloading Stand, hence no change to the value will be made on transition.
