### ISSUE TITLE
Suggestions / 1 "Bug" (?) Found

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#325]
**Customisation**
- Being able to change the position of the scrollbar (Left / Right)
- The command box color being separated from the primary colour

**Features**
- Spoofing Name/RID/IP/GeoIP to other stand users
- Custom root name on the address bar (ultimate only?)

**Bug(s)**
- Repairing other players vehicle cannot be done in chat by other players

**Comment by Sainan** [comment]
Only 1 thing per ticket, please.
