### ISSUE TITLE
Bad Russian Translate

### ISSUE THREAD

**Issue by insp1rat1on** [calamity-inc/Stand-Feedback#328]
1. Just a disgusting translation into Russian. It was done not by a human being, but by a translator..... 

2. Just inject Stand and change language to Russian

3. What does “Где” and “Что” mean? We need to replace “Где” with “Уведомления” because the list only displays notifications, that is the task of informing the player when players leave the session. Also, what does “Что”???? mean What “Что”? Instead of “Что” you should write “Отображать” because the list is meant to display how the player left, what does that have to do with “Что”?

![image](https://github.com/user-attachments/assets/e148340a-9ad2-40bf-baf3-3da5b17f8cf6)

"Уведомления социального клуба ЛС" "Социального клуба" Seriously? What's a social club? Why do we write “Социальный клуб” one day and “Social Club” the next? I know why, simply because it's translated by a translator, not a human. 

![image](https://github.com/user-attachments/assets/2d4fb895-19fa-4c8f-bfd6-b8b534eda233)

I actually put up with this translation for a long time, and didn't want to blame the person who makes it. But I just can't stand it anymore, and recently I found out that this person is being paid, which is just outrageous. This has been going on for a long time, every time with a new update we get just disgusting translation, which is actually hard to call translation. Ask in Russian Chat if you like the translation, people will definitely say no. If you think I'm writing this just because of 2 mistakes, it's not true. There are about 45+ errors in the translation. Please appoint a new translator or at least a person who will help him, because now the translation is often very incorrect and it is not clear what is where simply because the translator translates and not a person. 

I specifically logged into my old Github account to talk about this, just because Discord support closes my ticket for no reason time after time.... I would like to help with translation if needed.

**Comment by 99Anvar99** [comment]
> 1. Just a disgusting translation into Russian. It was done not by a human being, but by a translator.....
> 2. Just inject Stand and change language to Russian
> 3. What does “Где” and “Что” mean? We need to replace “Где” with “Уведомления” because the list only displays notifications, that is the task of informing the player when players leave the session. Also, what does “Что”???? mean What “Что”? Instead of “Что” you should write “Отображать” because the list is meant to display how the player left, what does that have to do with “Что”?
> 
> ![image](https://private-user-images.githubusercontent.com/139706371/361065930-e148340a-9ad2-40bf-baf3-3da5b17f8cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTMyNTYsIm5iZiI6MTcyNDQ1Mjk1NiwicGF0aCI6Ii8xMzk3MDYzNzEvMzYxMDY1OTMwLWUxNDgzNDBhLTlhZDItNDBiZi1iYWYzLTNkYTViMTdmOGNmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QyMjQyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTJiYTAyNzlhMGQzODUzODVmNjFmNDQzYzlmMTQ3Y2M5MGMwZDQxYWI5YzRmNzY0OGMxODI3ZmY1NzgyNjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jaCGpHsuWNeup8A2hfnVCxqD5Xq7BuCIPGis3-NHROs)
> 
> "Уведомления социального клуба ЛС" "Социального клуба" Seriously? What's a social club? Why do we write “Социальный клуб” one day and “Social Club” the next? I know why, simply because it's translated by a translator, not a human.
> 
> ![image](https://private-user-images.githubusercontent.com/139706371/361066480-2d4fb895-19fa-4c8f-bfd6-b8b534eda233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTMyNTYsIm5iZiI6MTcyNDQ1Mjk1NiwicGF0aCI6Ii8xMzk3MDYzNzEvMzYxMDY2NDgwLTJkNGZiODk1LTE5ZmEtNGM4Zi1iZmQ2LWI4YjUzNGVkYTIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QyMjQyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjQxYWVlYTNkY2YzMDg2NDJmYzJiMGNmOGJkM2QxMTZkMTFmMTcxMzAxNjAzYjg2YWNjMDU1MWEyMWZlNmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d7fFJQizHI-lCjBVdGt32Nekw8uoivJ51hdK8_UCAZo)
> 
> I actually put up with this translation for a long time, and didn't want to blame the person who makes it. But I just can't stand it anymore, and recently I found out that this person is being paid, which is just outrageous. This has been going on for a long time, every time with a new update we get just disgusting translation, which is actually hard to call translation. Ask in Russian Chat if you like the translation, people will definitely say no. If you think I'm writing this just because of 2 mistakes, it's not true. There are about 45+ errors in the translation. Please appoint a new translator or at least a person who will help him, because now the translation is often very incorrect and it is not clear what is where simply because the translator translates and not a person.
> 
> I specifically logged into my old Github account to talk about this, just because Discord support closes my ticket for no reason time after time.... I would like to help with translation if needed.

Я понимаю твое разочарование, и буду исправлять и корректировать. Спасибо что указал на это. 
Пожалуйста свяжитесь со мной в Дискорде если возникнут дополнительные вопросы. Спасибо!
