### ISSUE TITLE
SteamDeck Stand Link to PC

### ISSUE THREAD

**Issue by SlTHL0RD** [calamity-inc/Stand-Feedback#335]
A problem I’m having as well as other SteamDeck users using Stand with GTA V is that we Constantly have to re activate our Stand account per computer. 

(Example) My PC at home is logged into Stand, while I’m away from home and using the SteamDeck I’m currently unable to sign into Stand due to it being logged into my PC at home. (Constantly having to log into Stand per Device use / switch)

I would like to suggest a feature specifically for SteamDeck users where we are able to either use the same activation key as the pc at the same time or a way we could link our Stand account from pc to SteamDeck.

This would be a great addition for SteamDeck users because it is impossible to play GTA V on SteamDeck and pc at the same time due to how Steam works, so you could not share your Stand Account in any way. In addition this would make it a lot easier for SteamDeck users to be able to use Stand on the go without the hassle of logging in and out constantly.

I hope this feature will be considered and possibly added in the future. Thank you for your time!

**Comment by Sainan** [comment]
Simply unload Stand at home first, or regenerate the activation key if you forget to.
