### ISSUE TITLE
Error Shows Up When Opening Garage Option In Stand Menu

### ISSUE THREAD

**Issue by andyxa8** [calamity-inc/Stand-Feedback#336]
So Everytime I Open My Garage Options In Stand The Same Error Will Shows Up And My Game Freezing In A Short Time

[8/27/2024 9:12:15 AM] ---- ERROR INFORMATION BEGINS ----
Type: Possible cause of 'Bad Timing' errors
Message: Stand encountered an unexpected problem.
Stack Trace:
  00007FFA6ACD8B7E (Stand 24.8.12, 1337694200798B7E)
  00007FFA6ABD5384 (Stand 24.8.12, 1337694200695384)
  00007FFA6ABD57C4 (Stand 24.8.12, 13376942006957C4)
  00007FFA6AC69C56 (Stand 24.8.12, 1337694200729C56)
  00007FFA6A9DC888 (Stand 24.8.12, 133769420049C888)
  00007FFA6ABD750F (Stand 24.8.12, 133769420069750F)
  00007FFA6AC8854F (Stand 24.8.12, 133769420074854F)
  00007FFA6AC8835C (Stand 24.8.12, 133769420074835C)
  00007FFA6AC8836C (Stand 24.8.12, 133769420074836C)
  00007FFADA2DA521 (KERNELBASE.dll+000000000007A521): RegQueryInfoKeyA
  00007FFADC71091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFADC71091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[8/27/2024 9:12:15 AM] ---- ERROR INFORMATION ENDS ----

And This Is The Error When I Open My Garage Option Again

[8/27/2024 9:16:37 AM] ---- ERROR INFORMATION BEGINS ----
Type: Possible cause of 'Bad Timing' errors
Message: Stand encountered an unexpected problem.
Stack Trace:
  00007FFA6ACD8B7E (Stand 24.8.12, 1337694200798B7E)
  00007FFA6ABD5384 (Stand 24.8.12, 1337694200695384)
  00007FFA6ABD57C4 (Stand 24.8.12, 13376942006957C4)
  00007FFA6AC69C56 (Stand 24.8.12, 1337694200729C56)
  00007FFA6A9DC888 (Stand 24.8.12, 133769420049C888)
  00007FFA6ABD750F (Stand 24.8.12, 133769420069750F)
  00007FFA6AC8854F (Stand 24.8.12, 133769420074854F)
  00007FFA6AC8835C (Stand 24.8.12, 133769420074835C)
  00007FFA6AC8836C (Stand 24.8.12, 133769420074836C)
  00007FFADA2DA521 (KERNELBASE.dll+000000000007A521): RegQueryInfoKeyA
  00007FFADC71091A (ntdll.dll+000000000008091A): RtlUserFiberStart
  00007FFADC71091A (ntdll.dll+000000000008091A): RtlUserFiberStart
[8/27/2024 9:16:37 AM] ---- ERROR INFORMATION ENDS ----

**Comment by Sainan** [comment]
How many vehicles exactly do you have in your garage? I would appreciate if you could zip the whole folder and share it, maybe.

**Comment by andyxa8** [comment]
> How many vehicles exactly do you have in your garage? I would appreciate if you could zip the whole folder and share it, maybe.

I Want To Share My Vehicle Folder But RAR Format Does Not Support To Uploaded In Here, I Create A Zip File But The Size Is 69 MB And The Limit to Add Files In This Comment Is 25 MB.

So I See The Properties Tab On My Vehicles Folder And There Is 34.884 Files And 9.298 Folders In My Vehicles Folder. The Total Size Is 147 MB

Btw I Adding So Many Txt Vehicles Files From Stand Discord Which Is Shared By Other Members

**Comment by Sainan** [comment]
Okay, that is certainly... one way of using the feature. I've disabled the error reporting that you're seeing as a result of the excessive time it takes, but you will probably still notice lag as it tries to keep the list up-to-date with your filesystem. An SSD would certainly help here.
