### ISSUE TITLE
Features misleading users about their privacy

### ISSUE THREAD

**Issue by alessandromrc** [calamity-inc/Stand-Feedback#338]
The two features listed below are only local, and users should be made aware of this:

**Stand > Settings > Hide Information > Hide IP Address**
**Stand > Settings > Hide Information > Hide GeoIP**

I recommend adding descriptions to these features that clearly inform users that the action only affect their local view and **do not** prevent remote players from seeing their informations.

**Comment by Toph2T1** [comment]
I would have assumed that was fairly obvious with it being in the Stand settings submenu rather than in the Online submenu?

**Comment by alessandromrc** [comment]
> I would have assumed that was fairly obvious with it being in the Stand settings submenu rather than in the Online submenu?

Same is for me... although I have met people thinking it was some sort of protection :/

**Comment by Sainan** [comment]
I don't think it's as big of an issue as you're making it out to be, but I guess I can add a help text here to clarify the use-case of this.

![image](https://github.com/user-attachments/assets/a1f62431-16f3-4646-aa6e-89d0e85c09bb)

**Comment by alessandromrc** [comment]
> I don't think it's as big of an issue as you're making it out to be, but I guess I can add a help text here to clarify the use-case of this.
> 
> ![image](https://private-user-images.githubusercontent.com/63328889/362635655-a1f62431-16f3-4646-aa6e-89d0e85c09bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjc3NTYsIm5iZiI6MTcyNDkyNzQ1NiwicGF0aCI6Ii82MzMyODg4OS8zNjI2MzU2NTUtYTFmNjI0MzEtMTZmMy00NjQ2LWFhNmUtODlkMGU4NWMwOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwMzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYzFmOTU0YTA1ODIwYjlmOGI3ZjhjNzNiYzczNmI5ZDc5YjQ5Y2IzMTk0NDkwMmJmMWE0ZTAyYzg2YTM2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rBdPub7jJ2qBHV49V7yGQvf_Y3Xx1mw-1VdHR6_J28Q)

Looks perfectly fine.
