### ISSUE TITLE
set cursor position on non-mouse nav.

### ISSUE THREAD

**Issue by NickB926** [calamity-inc/Stand-Feedback#34]
the "set cursor position on non-mouse nav." feature works while pressing up but it does not when pressing down 

  

https://github.com/calamity-inc/Stand-Feedback/assets/86025185/3a8d29ab-f218-42b8-a802-fc49da85e79a

  
![image](https://github.com/calamity-inc/Stand-Feedback/assets/86025185/877f9c5c-126c-40b1-9a6c-f3369a459620)

**Comment by Sainan** [comment]
Can't reproduce
