### ISSUE TITLE
Buisness Manager Request

### ISSUE THREAD

**Issue by yKosa001** [calamity-inc/Stand-Feedback#341]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manage my in-game businesses manually. It takes a lot of time and distracts from other gameplay elements. Having to constantly check on supplies, start production, and sell products can be tedious and detracts from the overall gaming experience.

**Describe the solution you'd like**
I would like to see a Business Manager feature in the mod menu. This feature would automatically manage all in-game businesses like the Bunker, Nightclub, Cargo, and Motorcycle Club businesses. It should:

- Automatically sell products when they're ready.
- Refill supplies when needed.
- Increase production to maximize profits.
- Operate in the background while I’m playing, so I don’t need to worry about these tasks.

**Describe alternatives you've considered**
An alternative could be a semi-automatic system where the player is notified when an action needs to be taken, but it’s less ideal as it still requires manual intervention.

**Additional context**
This feature would greatly improve the quality for players who manage multiple businesses and prefer to focus on other aspects of the game.

**Comment by Sainan** [comment]
Business Manager is no longer maintained, and you are suggested to uninstall it.
