### ISSUE TITLE
Keep velocity after levitation (no-clip) disabled.

### ISSUE THREAD

**Issue by UnionProject** [calamity-inc/Stand-Feedback#342]
As title says, i want charachter to keep speed he gain after disabling no-clip.
1) you enable noclip
2) Speed up, still holding w key for example
3) While holding w key, you disable noclip
in result character keeps speed that he gain from no clipping and not just stop immideately
This can be implemented as toggle option in levitation settings for no clip preset

**Comment by TYpen11** [comment]
yeah this one im also looking for

**Comment by Sainan** [comment]
Will be added in a future update.
