### ISSUE TITLE
custom dlc wheels triggering false crash event

### ISSUE THREAD

**Issue by owleague** [calamity-inc/Stand-Feedback#343]
using any custom dlc wheel pack and applying it on any vehicle triggers a crash event on other stand users though it is completely harmless

steps to reproduce: use a wheel pack custom dlc or any dlc that adds custom wheels and other stand users will get a crash event

log of the event: [9/3/2024 5:14:58 PM] Crash Event (TF) from xxxx: Clone Update: AUTOMOBILE{id=298, wheel_type=0, wheel_mod=52}

**Comment by Sainan** [comment]
This is not a false-positive. There are cases where an out-of-bounds wheel can crash the game, but we will make it not sync an invalid value to other players.
