### ISSUE TITLE
"Block join" does not work as intended

### ISSUE THREAD

**Issue by isdzjfs** [calamity-inc/Stand-Feedback#349]
- **Obvious problem description**
  Block join still works when I'm not the host, which doesn't match the help text description
- **Steps to reproduce**
  Enable block join and wait for the player to join
- **Sufficient context**
  
![20240911070459](https://github.com/user-attachments/assets/a41d9121-2408-4ed5-8944-49f2df4e754b)

**Comment by owleague** [comment]
Block joins as non host will try to kick the player upon their join attempt. Block joins as host completely prevents them from joining the lobby

**Comment by Sainan** [comment]
Well, it does work as intended, but the help text is incorrect in this case.

**Comment by Sainan** [comment]
Will be updated with the next translation update (could take a while).

![image](https://github.com/user-attachments/assets/3269ea2b-c08a-4329-adeb-3c9757c887f8)
