### ISSUE TITLE
Add back Kick all for reg.

### ISSUE THREAD

**Issue by SypherQuantom** [calamity-inc/Stand-Feedback#35]
i know for a fact when you went into the players and all section you could do kick all but you cant do it anymore. add it back for reg and higher

**Comment by nuggettowin** [comment]
lmao

**Comment by Sainan** [comment]
![image](https://github.com/calamity-inc/Stand-Feedback/assets/63328889/806d4250-91b3-404c-8cc7-1fbaa527733d)

**Comment by Sainan** [comment]
Btw., "bealone" is an option. :)
