### ISSUE TITLE
Caught Acces violation

### ISSUE THREAD

**Issue by hubgitter356** [calamity-inc/Stand-Feedback#350]
hi so i didnt see anything like dm us the error so we can help" on discord so i think this is the right place to describe this error if not sorry. when im on game it regularly sometimes says caught an error check log.txt file. when i checked it it said Caught ACCESS_VIOLATION while reading from 000001C891CB4318 and a one with a different numbers Caught ACCESS_VIOLATION while writing to 00000000000035E8

**Comment by Sainan** [comment]
This is for reporting reproducible issues with Stand, not for general support.
