### ISSUE TITLE
Improve features such as: menu.readonly & menu.readonly_name

### ISSUE THREAD

**Issue by Lirniri** [calamity-inc/Stand-Feedback#351]
**Describe the solution you'd like**
Add the ability for user input to copy text.

**Additional context**
Base logic in Lua:
![image](https://github.com/user-attachments/assets/2bffaf4d-079c-430a-9044-965b0c4f0827)

Thanks in advance.

**Comment by Sainan** [comment]
The user should get a notification to let them know their click had an effect. Nowhere in Stand do we have such asinine behaviour and we don't intend to add it.
