### ISSUE TITLE
Session Browser is very slow to provide results / sometimes doesn't provide results at all

### ISSUE THREAD

**Issue by MidnightFries** [calamity-inc/Stand-Feedback#358]
When using Session Browser, results are either never returned or take several minutes to populate.

Troubleshooting:
  Set Stand to defaults
  Tried 24.8.13.dll  (24.9.1 is current)
  Disabled lua scripts
  Exited game and tried again
  Rebooted computer

Navigation:  Online -> Session Browser ->  (doesn't matter which settings are chosen)

Previously, the results were almost instant.  Now they're taking several minutes IF they populate at all.

**Comment by Sainan** [comment]
Can't reproduce. Also not really a Stand issue anyway because it's entirely subject to Rockstar Services.
