### ISSUE TITLE
Failed to inject DLL file

### ISSUE THREAD

**Issue by xNenji** [calamity-inc/Stand-Feedback#361]
I have completely turned off my Windows anti-virus program and allowed every threat that Stand needs. I have already tried to open Stand as an administrator but to no avail. I have checked my Stand folder and every file that Stand needs to work is there. I have already reinstalled Stand several times and restarted my PC. Please help!
![Stand Launchpad 1 9 2 18 09 2024 15_04_32](https://github.com/user-attachments/assets/25652f85-c2cd-4336-bd03-f735dca1dbbe)
![Stand Launchpad 1 9 2 18 09 2024 14_58_13](https://github.com/user-attachments/assets/1640b122-f64e-45f5-8ff3-2dfe4f143674)
![Stand Launchpad 1 9 2 18 09 2024 15_05_53](https://github.com/user-attachments/assets/a7ed87b1-a1e4-42c9-80c4-7336b51c52d5)
![Bin 18 09 2024 15_07_47](https://github.com/user-attachments/assets/ac400fbe-d8a4-4ae2-b368-49a703522ed3)
![Bin 18 09 2024 15_10_03](https://github.com/user-attachments/assets/ab485274-d552-4560-8f64-8a224908ffca)

**Comment by VideoClip98** [comment]
yea I got the same issue :(

**Comment by xNenji** [comment]
To solve the Problem you need to turn off BattleEye in your RockstarGames Launcher! See more in official Stand Discord: https://discord.com/channels/956618713157763072/956618713203896368

**Comment by Sainan** [comment]
The message in the Launchpad will be updated in the next Launchpad update: https://github.com/calamity-inc/Stand-Launchpad/commit/836a327f5cefe55798513f63e15b4b48df1aacca
