### ISSUE TITLE
Post-BattlEye update issue with disconnections when session host

### ISSUE THREAD

**Issue by wtfjet** [calamity-inc/Stand-Feedback#363]
When host of a lobby with Stand injected and host token spoofed, users will disconnect after about 90 seconds and will be presented a message about an being kicked due to an unsecure host. The lobby will then be empty.

**Comment by wtfjet** [comment]
Just a guess in the dark but there’s a call/response lock/key heartbeat thing missing from the exchange. Legit player clients are looking for the host to send the correct response and when they don’t get it, they are being kicked.

**Comment by Maritoguionyo** [comment]
I noticed if you block "network" and "outgoing syncs" on the host player, the host will no longer kick you

could probably use this knowledge to a fix to make you stay in the lobby

**Comment by Sainan** [comment]
Can't reproduce

**Comment by wtfjet** [comment]
Problem was corrected with PinkEye, no longer having disconnection issues. Please consider this as closed.
