### ISSUE TITLE
The game has encountered a critical error and may now require a restart.

### ISSUE THREAD

**Issue by xNenji** [calamity-inc/Stand-Feedback#368]
Even after restarting the game lags extremely.

Log:
Action: Continuing execution at next instruction.
[09/20/2024 10:47:49 PM] ---- ERROR INFORMATION STOPS ----
[09/20/2024 10:47:49 PM] ---- ERROR INFORMATION STARTS ----
Type: Uncaught INT_DIVIDE_BY_ZERO
Message: The game has encountered a critical error and may now require a restart.
Stack Trace: 00007FF6804C9A68 (GTA5.exe+00000000003D9A68, 00007FF794BB9A68) 00007FF68047D685 (GTA5.exe+000000000038D685, 00007FF794B6D685) 000 07FF6813E0B4F (GTA5.exe+00000000012F0B4F, 00007FF795AD0B4F) 00007FF6804AB26D (GTA5.exe+00000000003BB26D, 00007FF794B9B26D)
 00007FF680436BCE (GTA5.exe+0000000000346BCE, 00007FF794B26BCE) 00007FF68141DC52 (GTA5.exe+000000000132DC52, 00007FF795B0DC52) 74 (KERNEL32.DLL+0000000000017374): BaseThreadInitThunk 00007FF8D12FCC91 (ntdll.dll+000000000004CC91): RtlUserThreadStart 00007FF8D12FCC91 (ntdll.dll+000000000004CC91): RtlUserThreadStart

**Comment by Sainan** [comment]
Needs steps to reproduce.
