### ISSUE TITLE
A toggle to turn off the warning of taking hosts

### ISSUE THREAD

**Issue by Randompasserbygamer** [calamity-inc/Stand-Feedback#370]
With the help of pinkeye, it is no longer necessary to take the host in every session.

Besides, it would also be quite annoying for the warning to keep popping up every few seconds when you are just doing a job hosted by a legit player and you would fail the mission by taking the host just to remove the warning. So it would be better if you can have a switch to turn off the warning.

An alternative could be that the warning will appear depending on whether you have the battleye disabled as stand runs a thorough detection for this.

**Comment by LemonHazeMan** [comment]
PLEASE (BUMP)

**Comment by Sainan** [comment]
This is a bug, it will be fixed soon.
