### ISSUE TITLE
Disrespect Next Host

### ISSUE THREAD

**Issue by mehgancangweh** [calamity-inc/Stand-Feedback#373]
Within [1.69-3337](https://steamdb.info/patchnotes/15810442/) update this host disrespecting blud in the next queue.
i hope can get around with this gang, yk
<details><summary>Can still be a host without be, just not instant as before (Sorted as lowest RID):</summary>

![](https://github.com/user-attachments/assets/7cf48b66-a6b8-412c-abe7-f69278db8c1c)</details>

**Comment by Sainan** [comment]
Please read our announcements for more information
