### ISSUE TITLE
Free purchase like cherax

### ISSUE THREAD

**Issue by JohnDoe464d** [calamity-inc/Stand-Feedback#379]
**Is your feature request related to a problem? Please describe.**
It would be much less risky than making money with casino or musinessbanager especially rn bc of battleye.

**Describe the solution you'd like**
Just make a feature or a script for stand with the free purchase option.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by isytrana** [comment]
Sainan already said that she won't do it because this kind of options get detected fast.
Even though it's been months Cherax has it and Sainan could for sure try to get it aswell since no one got banned for sure because of that feature in particular.
