### ISSUE TITLE
Wrong marker crash

### ISSUE THREAD

**Issue by latiao-1337** [calamity-inc/Stand-Feedback#38]
- **Obvious problem description**
Wrong marker crash I was playing free mode with a friend (I 110% guarantee he is not a cheater) and he reported a crash to me when he entered the room

SCRIPT_WORLD_STATE_EVENT: 0110111001000011101010101010101111101000001011011000010001000011010110000000000010000001100111110111000000011110101101011001001100001101100000000000000000000000000000000000000011000101000110011100000001010001110001000000000000000000000001010001110000110011001000000010100011111, Subtype: Rope, {Type: 1, Init Length: 0, Min Length: 0.997955, Max Length: 0.997955}

- **Steps to reproduce**
Probability of occurrence
- **Sufficient context**
![图片](https://github.com/calamity-inc/Stand-Feedback/assets/146958060/b82d0dc8-8b4d-4309-ab15-8375f6300a56)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
