### ISSUE TITLE
HSW modification 

### ISSUE THREAD

**Issue by EastMan1109** [calamity-inc/Stand-Feedback#380]
**Is your feature request related to a problem? Please describe.**
Some sport cars in GTA is really slow. It will be cool if i can get HSW mode for at least cars that support HSW from new gen

**Describe the solution you'd like**
HSW mode for cars like Turismo Classic. Maybe HSW painting as well

**Describe alternatives you've considered**
Maybe engine boost(for 2.00) and adding high speed. 

**Additional context**
I saw that function already in menyoo 2.0, so i guess it not that hard to do it in stand too

**Comment by Sainan** [comment]
HSW is not in the PC version. If you mean the speed boost, I'm pretty sure you just get that when using `tune`.
