### ISSUE TITLE
Issue streaming other players. (Some players are invisible for long durations of time session time, and then they re-appear, and sometimes people are visible, but later on in the session turn invisible.

### ISSUE THREAD

**Issue by yellowdude040212** [calamity-inc/Stand-Feedback#390]
I am having an issue with players being invisible, but other visible, then sometimes they become visible again, and etc. Whenever i try to follow someone they go invisible on the screen but not the map/minimap. Just  wondering if theres a fix for This.

**Comment by Sainan** [comment]
This is not a support channel.
