### ISSUE TITLE
FSL and "This feature is not available now. Please come back later."

### ISSUE THREAD

**Issue by Maritoguionyo** [calamity-inc/Stand-Feedback#395]
**Is your feature request related to a problem? Please describe.**
I feel like doing stuff while having FSL should allow you for example, do stuff that gets you "timed out"

**Describe the solution you'd like**
one example is rigging the casino, always winning on the slot machines causes the timeout, which I think should be removed if Stand detects FSL being used

**Comment by Sainan** [comment]
You can just give yourself money with FSL: https://www.unknowncheats.me/forum/grand-theft-auto-v/616977-fsl-local-gtao-saves.html
