### ISSUE TITLE
aimbot low quality

### ISSUE THREAD

**Issue by xczsonn** [calamity-inc/Stand-Feedback#4]
**Is your feature request related to a problem? Please describe.**
The current menu's aimbot is severely stuttery, unnatural, and has poor recognition, which detracts from the experience of the game.

**Describe the solution you'd like**
We want you to completely rebuild your aimbot. Add hostile NPCs to goal setting, improve aimbot accuracy.

**Describe alternatives you've considered**
The aimbot for the cherax menu is very high quality, so it would be nice to see something based on it, at least as good as the aimbot for the 2take1 menu.

**Additional context**
Some people call aimbots a useless feature, but they're an important part of the fun of the game.

**Comment by ItsEntDev** [comment]
No offense, but aimbot is such a useless feature. It's a cheat that is only useful for gaslighting people into thinking they're worse than they really are. It doesn't even qualify as a trolling feature, it's just really annoying. (I'm not Sainan though so I don't know what she thinks)

**Comment by Zaptize** [comment]
then use magic bullets or get better at aiming

**Comment by xczsonn** [comment]
> No offense, but aimbot is such a useless feature. It's a cheat that is only useful for gaslighting people into thinking they're worse than they really are. It doesn't even qualify as a trolling feature, it's just really annoying. (I'm not Sainan though so I don't know what she thinks)

It's very important to me because i use 2take1 together only for this.

**Comment by xczsonn** [comment]
> then use magic bullets or get better at aiming

Why use the menu when you can do everything yourself?

**Comment by ItsEntDev** [comment]
> > No offense, but aimbot is such a useless feature. It's a cheat that is only useful for gaslighting people into thinking they're worse than they really are. It doesn't even qualify as a trolling feature, it's just really annoying. (I'm not Sainan though so I don't know what she thinks)
> 
> It's very important to me because i use 2take1 together only for this.



> > then use magic bullets or get better at aiming
> 
> Why use the menu when you can do everything yourself?

I'm saying this attitude is stupid. You haven't actually provided a reason why aimbot is a good feature.

**Comment by Zaptize** [comment]
> > then use magic bullets or get better at aiming
> 
> Why use the menu when you can do everything yourself?

can you not use a mouse, is this really a issue

**Comment by NotKNow21Br** [comment]
for real,i use another menu only cause of the aimbot...
