### ISSUE TITLE
Nightclub stock problem

### ISSUE THREAD

**Issue by GANDARFE** [calamity-inc/Stand-Feedback#408]
(sorry for bad english)
The warehouse isn’t generating nothing and I can't edit the technicians. When I try to reassign them, I get an error, as if one of them is managing ALL the businesses at the same time. I even bought another nightclub in a different location, and the issue still persists. And that's a Stand problem, because if I enter in GTA Online without Stand, the Nightclub runs normally.

https://github.com/user-attachments/assets/90708bb8-ea67-4f2d-95fe-2c3358979eb9

**Comment by Sainan** [comment]
Does this happen on default state?

**Comment by GANDARFE** [comment]
Without Stand? No, if I enter in GTA without stand, the problem just go
away.

Em dom., 3 de nov. de 2024 às 17:54, Sainan ***@***.***>
escreveu:

**Comment by Sainan** [comment]
This isn't a support channel.
