### ISSUE TITLE
Fatal Error apon blowing up any vehicle.

### ISSUE THREAD

**Issue by Zaptize** [calamity-inc/Stand-Feedback#415]
Whenever I decide to blow up a vehicle (I found this out through delete personal vehicle) it causes a fatal error, and this is consistently happening no matter what I tried, I have already tried loading with nothing enabled, default, wiping the bin folder, and reinstalling the game and nothing has sufficiently changed other than when it would crash me before, it has just turned into a few seconds of lag and a fatal error. This is also not platform specific as I had this happen on epic, rockstar, and on steam after clean installs.

I have 0 idea how to reproduce this as nobody knows what is causing it other than it is just if a vehicle explodes, not even a specific one, just any vehicle in general.

The log of the error:
Type: Uncaught ACCESS_VIOLATION while reading from FFFFFFFFFFFFFFFF
Message: The game had a fatal error and may need a restart now.
Stack Trace:
  00007FF6C3F51A24 (GTA5.exe+0000000001041A24, 00007FF781F41A24)
  00007FF6C3F6C254 (GTA5.exe+000000000105C254, 00007FF781F5C254)
  00007FF6C3F6B207 (GTA5.exe+000000000105B207, 00007FF781F5B207)
  00007FF6C440475E (GTA5.exe+00000000014F475E, 00007FF7823F475E)
  00007FF6C35EE16C (GTA5.exe+00000000006DE16C, 00007FF7815DE16C)
  00007FF6C35EF008 (GTA5.exe+00000000006DF008, 00007FF7815DF008)
  00007FF6C384F393 (GTA5.exe+000000000093F393, 00007FF78183F393)
  00007FF6C386C26D (GTA5.exe+000000000095C26D, 00007FF78185C26D)
  00007FFD523B03D2 (Stand 24.12.1, 13376942006E03D2)
  00007FF6C4565C8F (GTA5.exe+0000000001655C8F, 00007FF782555C8F)
  00007FF6C2F38704 (GTA5.exe+0000000000028704, 00007FF780F28704)
  00007FF6C2F31DEF (GTA5.exe+0000000000021DEF, 00007FF780F21DEF)
  00007FF6C4565898 (GTA5.exe+0000000001655898, 00007FF782555898)
  00007FF6C2F11494 (GTA5.exe+0000000000001494, 00007FF780F01494)
  00007FF6C4236C97 (GTA5.exe+0000000001326C97, 00007FF782226C97)
  00007FF6C475CDD8 (GTA5.exe+000000000184CDD8, 00007FF78274CDD8)
  00007FFE08947374 (KERNEL32.DLL+0000000000017374): BaseThreadInitThunk
  00007FFE09D5CC91 (ntdll.dll+000000000004CC91): RtlUserThreadStart
  00007FFE09D5CC91 (ntdll.dll+000000000004CC91): RtlUserThreadStart
Action: Continuing execution at next instruction.
[12/5/2024 10:25:49 PM] ---- ERROR INFORMATION ENDS ----

**Comment by Sainan** [comment]
Can't reproduce.
