### ISSUE TITLE
a ccouple of features got buged after last updates.

### ISSUE THREAD

**Issue by holy-fock** [calamity-inc/Stand-Feedback#418]
1-  **Vehicle > Personal Vehicles > (car name) > Request** not working if the vehicle is destroyed.

2- **Online > Session > Session Scripts > Run Script > Freemode Activities > Challenges** only working the first time it got activated then its just bugged and has no effect anymore : 
- cant stop challenges
- cant edit Score
- cant change the challenge

3- **Players > All Players > Crash > Elegant** Crashes you, not all

**Comment by Sainan** [comment]
One bug per ticket, please.
