### ISSUE TITLE
Unable to punch NPC's after loading a profile

### ISSUE THREAD

**Issue by McQueeny99** [calamity-inc/Stand-Feedback#436]
After loading the profiles I made, I am unable to punch/melee NPC's. My character swings at them, but the fist goes straight through and does nothing. I have this issue on every profile that I have made, and am unable to find the cause.

To reproduce, just save a heavily modded profile and then press load, run toward an NPC and try to hit them.

Thanks for your time.

**Comment by Sainan** [comment]
Given that you say you don't have this issue with the default state, this is clearly an issue with you enabling some shit in your profile and then forgetting about it. This isn't a support channel.

**Comment by McQueeny99** [comment]
Thing is, I took my time carefully making my profile from scratch, testing
throughout the process. I only found the issue after I LOADED the profile.
I am certain my settings have nothing to do with it.

**Comment by TeleportForward** [comment]
looking for player for apartment mission mastermind and doomsday hard difficulty，i like drive Vigilante to rocket speed！my socialclub user name is FROMathinkYoullD
with battleye on normally Play
