### ISSUE TITLE
VPN not detected

### ISSUE THREAD

**Issue by isytrana** [calamity-inc/Stand-Feedback#439]
I am using Proton VPN on the server NL#494, Stand doesn't detect me as using a VPN.
Idk what I need to send here for this kind of bugs

**Comment by Sainan** [comment]
What's the IP address?

**Comment by isytrana** [comment]
![image](https://github.com/user-attachments/assets/6584cea6-ea0c-452c-9d36-2dc7a9f46a42)
Mb i forgot the screenshot.

**Comment by Sainan** [comment]
Thanks. Will be fixed.

**Comment by TeleportForward** [comment]
looking for player for apartment mission mastermind and doomsday hard difficulty，i like drive Vigilante to rocket speed！my socialclub user name is FROMathinkYoullD
with battleye on normally Play
