### ISSUE TITLE
Deleting current attackers doesn't prevent queued attackers from spawning

### ISSUE THREAD

**Issue by shadow7483147** [calamity-inc/Stand-Feedback#46]
- **Steps to reproduce**
1. Spawn at least 20 attackers on somebody. Use a single-seat vehicle.
2. Immediately back out of the menu and delete the attackers.
3. Attackers will continue spawning despite you deleting them.
4. You must delete after the spawning is complete to fully delete the attackers.

- **Expected behavior**
Attackers should stop spawning as soon as you press the button to delete them.

**Comment by awaseru** [comment]
thanks for the report! will be fixed in the next update.
