### ISSUE TITLE
Skip Swoop Down will cause infinite loading

### ISSUE THREAD

**Issue by latiao-1337** [calamity-inc/Stand-Feedback#49]
- **Obvious problem description**
If your spawn point is indoors (such as an apartment), opening Online>Transitions>Skip Swoop Down will cause infinite loading
- **Steps to reproduce**
Open Online>Transitions>Skip Swoop Down
Change the spawn point to indoors in the game
Enter the new lobby
- **Sufficient context**
N/A

**Comment by latiao-1337** [comment]
The same problem will occur
Online>Transitions>Seamless Session Switching>Seamless Session Switching

**Comment by Sainan** [comment]
Yeah, it's a known issue. The problem is that we don't know if we're gonna load into an interior, so we'd have to wait, but if we were to wait, the feature would be worse for it. So, really, it's just on you to manage your usage of these features.
