### ISSUE TITLE
Player History Block Join is enabled when not session host

### ISSUE THREAD

**Issue by nuggettowin** [calamity-inc/Stand-Feedback#52]
The help text for the block join function states "this will only have an effect when you're the session host". However, when I am not session host and someone whom I've join blocked in my player history attempts to join , they are still unable to join, and Stand provides the "blocked xxx from joining because of Player Join Reactions" notification

**Comment by Sainan** [comment]
You may be confused. There is no way to block joins as non-host. If you have the 'H' tag, you are the session host. The 'S' tag for Script Host is unrelated.
