### ISSUE TITLE
116 show model punishment

### ISSUE THREAD

**Issue by Lechom** [calamity-inc/Stand-Feedback#53]
Issue: The show model Punishment only works for when you are shooting. The one when you are aiming doesnt work, you still need to shoot to show the model name.

**Comment by Sainan** [comment]
It does work. It shows it in your info text when aiming.

**Comment by Lechom** [comment]
> It does work. It shows it in your info text when aiming.

ohhh alright my bad

**Comment by Lechom** [comment]
but it still shows it when you shoot on the stand notifications even tho I only enabled when aiming. Should it be like that or?

**Comment by Lechom** [comment]
> It does work. It shows it in your info text when aiming.

but it still shows it when you shoot on the stand notifications even tho I only enabled when aiming. Should it be like that or?

**Comment by Sainan** [comment]
Yes, aim punishments apply when shooting.

**Comment by Lechom** [comment]
> Yes, aim punishments apply when shooting.

ok, thx for the fast answers

**Comment by Lechom** [comment]
> Yes, aim punishments apply when shooting.

oh and another thing, for some reason when I shoot with model punishment now, I get "caught an exception error"

[17.06.2024 17:41:01] ---- ERROR INFORMATION BEGINS ----
Type: Caught ACCESS_VIOLATION while reading from 0000025196168673
Message: Caught an exception.
Stack Trace:
  00007FFB304AF020 (Stand 116, 133769420074F020)
  00007FFB30441A02 (Stand 116, 13376942006E1A02)
  00007FFB304DF65F (Stand 116, 133769420077F65F)
  00007FFB3043BFAB (Stand 116, 13376942006DBFAB)
  00007FFB3043D664 (Stand 116, 13376942006DD664)
  00007FFB304CE26F (Stand 116, 133769420076E26F)
  00007FFB304CE07C (Stand 116, 133769420076E07C)
  00007FFB304CE08C (Stand 116, 133769420076E08C)
  00007FFBB9CF44AB (KERNELBASE.dll+00000000000844AB): ChangeTimerQueueTimer
  00007FFBBC538124 (ntdll.dll+0000000000088124): RtlUserFiberStart
  00007FFBBC538124 (ntdll.dll+0000000000088124): RtlUserFiberStart
[17.06.2024 17:41:01] ---- ERROR INFORMATION ENDS ----

**Comment by Lechom** [comment]
sometimes not tho
