### ISSUE TITLE
Gifting cars is bugged 

### ISSUE THREAD

**Issue by Cjoy329** [calamity-inc/Stand-Feedback#59]
Gifting cars won't work.

**Comment by LordByronRS** [comment]
It works without a problem for me. Make sure that you are not the script host. If it still doesn't work, give us a bit more information.

**Comment by MJP666NL** [comment]
It is still possible if you forge the model for yourself.
Make sure you have a garage that is full, with at least one car that you don't care about losing.
You can fill up a 2 car garage with free cars.
Then spawn the vehicle that you want to get for free.
Forge the model for yourself and drive up to the garage door.
When you get the notification screen that the garage is full you need to unselect the forge option and only then press enter to enter the garage.
Then choose the car that you want to replace.
If done correctly you will have the desired car, if done incorrectly (probably forgot to unselect the forge option) then you will probably see a motorcycle.
This is my experience atleast.
This way you will not be able to give a car to friends, but you are able to get free cars yourself.
