### ISSUE TITLE
Patch a new crash

### ISSUE THREAD

**Issue by NuclearCherry7** [calamity-inc/Stand-Feedback#6]
There is a new crash which is currently unblocked by stand it is done by deleting the hud of the target. I would like to see this patched and for stand to remain uncrashable

**Comment by Zaptize** [comment]
do you have a log of what happened, it could have been a fatal error or something

**Comment by Prisuhm** [comment]
> There is a new crash which is currently unblocked by stand it is done by deleting the hud of the target. I would like to see this patched and for stand to remain uncrashable

if you're referring to the bubble stuff which was recently added to YimMenu I am 100% sure it has already been patched.
