### ISSUE TITLE
Menus mod kill is no longer blocked by menu

### ISSUE THREAD

**Issue by Kikok516** [calamity-inc/Stand-Feedback#62]
Title

**Comment by isytrana** [comment]
You would probably try to describe what it is precisely ?

**Comment by Kikok516** [comment]
Option "Players > Player[H] > Trolling > Kill" is no longer blocked if used on another Stand user which was the case in the past. Protection which used to block this is "Online > Protections > Events > Modded Damage Event"

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
