### ISSUE TITLE
Repairing whilst going over 179mph causes the vehicle to come to a dead stop

### ISSUE THREAD

**Issue by Decuwu** [calamity-inc/Stand-Feedback#63]
# Bug Description
- When going over 179mph (288kmh) if you repair your car, it will come to a sudden stop

# Replicate
- Get into a vehicle, i tested with a car and a jet and exceed 179mph (288kmh). Once you are, repair your vehicle and it will come to a stop

# Additional Info
- Attached video showcases me reaching over 179mph and repairing my vehicle
- On the second go i was holding the button to see when it triggers

- Auto repair works as intended and this is solely the Fix Vehicle feature

https://github.com/calamity-inc/Stand-Feedback/assets/112495774/e9bac8e8-2cd3-44b7-ae47-0452e375bbd8

**Comment by awaseru** [comment]
thanks for the report! will be fixed next update.
