### ISSUE TITLE
Vinnila mode

### ISSUE THREAD

**Issue by Destroyer997** [calamity-inc/Stand-Feedback#64]
A toggle to use vinnila mode wich would disable all mod features until turned off for when the user wants a vinnila experice with all the protections

**Comment by AssemblyLangFTW** [comment]
Unless I'm missing something.. why can't you use Stand in the default state?

**Comment by Destroyer997** [comment]
Then i have to enable and disable every thing again unless there is a easier way

**Comment by AssemblyLangFTW** [comment]
> Then i have to enable and disable every thing again unless there is a easier way

Save everything you use to a profile, then load that profile

**Comment by Destroyer997** [comment]
If i change profiles and back it messes it up for me the last view times i did that but ill mess aroumd with it agaim when i play thx
