### ISSUE TITLE
Crashing At Random

### ISSUE THREAD

**Issue by AssemblyLangFTW** [calamity-inc/Stand-Feedback#65]
Whenever just strolling around in GTA Online, my game crashes at random. There is seemingly no way to reproduce, it kind of just happens, although this time it was after I got kicked, I rejoined and then crashed.

Log:

[6/22/2024 2:50:21 PM] ---- ERROR INFORMATION BEGINS ----
Type: Uncaught ACCESS_VIOLATION while reading from FFFFFFFFFFFFFFFF
Message: The game had a fatal error and may need a restart now.
Stack Trace:
  00007FFAF4CC99D0 (nvwgf2umx.dll+00000000005799D0): NVAPI_Thunk
  00007FFAF4CBC030 (nvwgf2umx.dll+000000000056C030): NVAPI_Thunk
  00007FFAF4CC75AF (nvwgf2umx.dll+00000000005775AF): NVAPI_Thunk
  00007FFAF4CC750F (nvwgf2umx.dll+000000000057750F): NVAPI_Thunk
  00007FFAF4CBBEDD (nvwgf2umx.dll+000000000056BEDD): NVAPI_Thunk
  00007FFAF51271FA (nvwgf2umx.dll+00000000009D71FA): NVDEV_Thunk
  00007FFAF563E1FE (nvwgf2umx.dll+0000000000EEE1FE): SetDependencyInfo
  00007FFB06107344 (KERNEL32.DLL+0000000000017344): BaseThreadInitThunk
  00007FFB07CE26B1 (ntdll.dll+00000000000526B1): RtlUserThreadStart
  00007FFB07CE26B1 (ntdll.dll+00000000000526B1): RtlUserThreadStart
Action: Continuing execution at next instruction.
[6/22/2024 2:50:21 PM] ---- ERROR INFORMATION ENDS ----

**Comment by BKiri** [comment]
looks like game issue instead of stand's tho. do you have any mods installed?

**Comment by AssemblyLangFTW** [comment]
> looks like game issue instead of stand's tho. do you have any mods installed?

No, I'm just using basic Lua scripts like JinxScript and Constructor

**Comment by Sainan** [comment]
Not a Stand issue
