### ISSUE TITLE
The print() function only prints the first argument when multiple are given.

### ISSUE THREAD

**Issue by Toph2T1** [calamity-inc/Stand-Feedback#68]
Using the print() function with multiple arguments only prints the first argument.

Example:
print("this", "is", "a", "test") will only print "this". 

I am unsure if this is normal behavior for Pluto, but in vanilla Lua each argument would normally be printed with a tab in-between, but stand seemingly ignores anything but the first argument completely. 
![Untitled](https://github.com/calamity-inc/Stand-Feedback/assets/97222777/31567c5b-6eb1-4120-94c3-44d05eaad590)

**Comment by Sainan** [comment]
`print` is not available in Stand due to having no TTY. We simply make it an alias for `util.log`, which only accepts a single argument.
