### ISSUE TITLE
Love letter kick causing exception

### ISSUE THREAD

**Issue by Decuwu** [calamity-inc/Stand-Feedback#73]
# Bug description
- when using love letter on someone, stand throws an exception and prevents you using the kick again with a notification "You're doing this too quickly..."

# How to recreate
- i just joined a lobby, chose someone and love letter kicked them

# Additional info
- Below is the error i recieved

[25/06/2024 16:56:50] ---- ERROR INFORMATION BEGINS ----
Type: Caught ACCESS_VIOLATION while reading from FFFFFFFFFFFFFFFF
Message: Caught an exception.
Stack Trace:
  00007FFE8FF80EE9 (Stand 116.1, 13376942003F0EE9)
  00007FFE8FEFDCFD (Stand 116.1, 133769420036DCFD)
  00007FFE9025088F (Stand 116.1, 13376942006C088F)
  00007FFE9030096F (Stand 116.1, 133769420077096F)
  00007FFE9030077C (Stand 116.1, 133769420077077C)
  00007FFE9030078C (Stand 116.1, 133769420077078C)
  00007FFEF35544AB (KERNELBASE.dll+00000000000844AB): ChangeTimerQueueTimer
  00007FFEF6058124 (ntdll.dll+0000000000088124): RtlUserFiberStart
  00007FFEF6058124 (ntdll.dll+0000000000088124): RtlUserFiberStart
[25/06/2024 16:56:50] ---- ERROR INFORMATION ENDS ----

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
