### ISSUE TITLE
Disable Dripfeeding isn't prevent car despawns nor appearing on websites

### ISSUE THREAD

**Issue by Decuwu** [calamity-inc/Stand-Feedback#74]
Disable Dripfeeding at `online > enhancements > disable dripfeeding` is not preventing the car despawning, nor is it displaying the vehicles on the website to purchace (i believe it's supposed to do the latter im not sure)

**Comment by Sainan** [comment]
What vehicle(s) do you experience this with?

**Comment by Decuwu** [comment]
all vehicles are their spawn name

castigator
dominator10
driftcypher
driftvorschlag
pipistrello
pizzaboy
poldominator10
vorschlaghammer

this isn't all the unreleased vehicles, the only two it seems to work for are the:

driftnebula
driftsentinel

They dont despawn in a specific time, some are faster than others and sometimes the same car can let you drive it for 5 seconds

**Comment by Sainan** [comment]
I realise "disable dripfeeding" was not updated correctly. Will be fixed.
