### ISSUE TITLE
French translation issues/Mistranslation

### ISSUE THREAD

**Issue by yorik100** [calamity-inc/Stand-Feedback#75]
Innacurate translations
- **Obvious problem description**
  - "En Ligne -> Protection -> Hôte Kicks -> Contrôlé -> Notification Quand La Lettre D'amour À Kick" <-> "Notification Quand La Lettre D'amour A Kick", in this case "À" should be "A" as the verb is "avoir", "Elle A Kick"
  - "Test est maintenant classifier en Moddeur" <-> "Test est maintenant classifié en Moddeur", in this case "Test est (maintenant) clasiffié"

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
