### ISSUE TITLE
getting kicked after update

### ISSUE THREAD

**Issue by Lechom** [calamity-inc/Stand-Feedback#76]
since the new update now, when i join a public lobby even tho im host everytime, i get kicked from the lobby and it shows that everyone left after like 20 to 30 seconds.

**Comment by Sainan** [comment]
Can't reproduce

**Comment by Lechom** [comment]
> Can't reproduce

I think its when you spoof host token and get host with it, other people expereinced the same

**Comment by Sainan** [comment]
I am spoofing my host token
