### ISSUE TITLE
Co-Load is broken

### ISSUE THREAD

**Issue by DerAnimedude** [calamity-inc/Stand-Feedback#78]
i wanna say that the Co-Loads arent working anymore 
i have Stand and 2Take1 and after the update on the 25.6.24 i cant Co-Load them no more i tried every possible thing i reseted both and tried them without the other one and in other inject order but still no sign of funtion i only get the error H9.

and i wanted to say that i also noticed some flaws in the previous version too sometime it just crashed my game on inject so i would appreciate if you guys could look at it and fix the Co-Load problems

regards Animedude

**Comment by Sainan** [comment]
Will be fixed in the next update.
