### ISSUE TITLE
Vroom Lua script 

### ISSUE THREAD

**Issue by Toxicfufu** [calamity-inc/Stand-Feedback#8]
Could we add horn Boost sync to other players like Cherax does in a lua script / and many more other troll features and could we bypass the acceleration limit on poeples vechile to give them extra boost ?

**Comment by ji8sw** [comment]
this isnt the place to request lua scripts

**Comment by Prisuhm** [comment]
You can already increase the speed of other players cars in Friendly > Vehicle > Engine Power Multiplier

**Comment by Toxicfufu** [comment]
> You can already increase the speed of other players cars in Friendly > Vehicle > Engine Power Multiplier

The problem is can we bypass the limit ? And add horn click sync for other players if possible like, cherax does on the vroom section they gain like 600mph horn boost 😅
