### ISSUE TITLE
friend cant to jon me, session is full but it isnt 

### ISSUE THREAD

**Issue by Ayenced** [calamity-inc/Stand-Feedback#88]
when i the host of session, my friend cant join to me (he dont using any mods), gta always telling him the session is full (right now is 13 players on my session). any solution?

**Comment by Sainan** [comment]
Are you co-loading?

**Comment by Ayenced** [comment]
what is this?

**Comment by Sainan** [comment]
Well, I can't reproduce this issue.

**Comment by Sainan** [comment]
Nevermind, we identified an issue related to this, and it will be fixed in the next update.
