### ISSUE TITLE
session is always full for others when joining me even if im by my self

### ISSUE THREAD

**Issue by DoctorFLEXoChan** [calamity-inc/Stand-Feedback#90]
A good issue report has _at least one_ of these:
- **Obvious problem description**
  - For example: "I expected Immortality to make me immortal, but I still died."
- **Steps to reproduce**
- **Sufficient context**
  - For things related to detections, the things in the parentheses.
  - For false-positives, a log of the event.
  - Stack trace, if applicable, and if Stand's DLL is a major part of it.

**Comment by Sainan** [comment]
Are you co-loading?

**Comment by Sainan** [comment]
Nevermind, we identified an issue related to this, and it will be fixed in the next update.
