### ISSUE TITLE
The options for making the 15 million hits are failing, they do not put the percentages that should be given for the 15 million 

### ISSUE THREAD

**Issue by Destroyedtanker** [calamity-inc/Stand-Feedback#91]
The options for classic hits / 15 million hits are failing, they don't put the percentages they should

**Comment by Sainan** [comment]
What?

**Comment by Destroyedtanker** [comment]
That the 15 million punch (heist control) classic punches is failing

**Comment by Sainan** [comment]
Heist Control is not maintained by us.
