### ISSUE TITLE
Gift Spawned Vehicle is patched

### ISSUE THREAD

**Issue by yuriy078g** [calamity-inc/Stand-Feedback#92]
Tested on public sessions, wasn't host or script host

Vehicle just removed right after I clicked Gift Spawned Vehicle

**Comment by Sainan** [comment]
Yeah, will be removed in the next update.

**Comment by Lechom** [comment]
> Yeah, will be removed in the next update.

also ban kick is patched I think

**Comment by Sainan** [comment]
Yeah, will also be removed next update. :)
