### ISSUE TITLE
Wrong marker KICK (S3)

### ISSUE THREAD

**Issue by latiao-1337** [calamity-inc/Stand-Feedback#93]
- **Obvious problem description**
Wrong marker KICK S3
My friend and I were playing free mode and to make sure he was 110% not cheating

{0: 2273252511303 (1214811719), 1: 2272037699589 (5), 2: 32768, 3: 0, 4: 2276332666879 (-1), 5: 4, 6: 2272037699808 (224), 7: 27, 8: 63, 9: 5212462810544035174 (862541158), 10: 3555677965179317075 (1110600531), 11: 89534187586418 (1299334002), 12: 0, 13: 0, 14: 0, 15: 2284922601471 (-1), 16: 2167499, 17: 2276332666879 (-1)}

- **Steps to reproduce**
N/A

- **Sufficient context**
![图片](https://github.com/calamity-inc/Stand-Feedback/assets/146958060/7b90e015-2e59-4f23-b225-651487b6a6e4)

**Comment by Sainan** [comment]
Thanks for the report, will be fixed in the next update.
