### ISSUE TITLE
unexpected problem

### ISSUE THREAD

**Issue by Lechom** [calamity-inc/Stand-Feedback#97]
I was just afking and randomly got this from stand "Message: Stand encountered an unexpected problem". Here the Log:

[26.06.2024 14:08:46] ---- ERROR INFORMATION BEGINS ----
Type: Game attempted to reuse an object id
Message: Stand encountered an unexpected problem.
Stack Trace:
  00007FFA96E91A1E (Stand 116.3, 13376942007C1A1E)
  00007FFA96D8E934 (Stand 116.3, 13376942006BE934)
  00007FFA96D8ED74 (Stand 116.3, 13376942006BED74)
  00007FFA96AA315A (Stand 116.3, 13376942003D315A)
  00007FF77AD40EC5 (GTA5.exe+00000000011B0EC5, 00007FF638BD0EC5)
  00007FF77AC4F639 (GTA5.exe+00000000010BF639, 00007FF638ADF639)
  00007FF77AB69CE2 (GTA5.exe+0000000000FD9CE2, 00007FF6389F9CE2)
  00007FF77AB8AE51 (GTA5.exe+0000000000FFAE51, 00007FF638A1AE51)
  00007FF77AAD5936 (GTA5.exe+0000000000F45936, 00007FF638965936)
  00007FF77AB1537C (GTA5.exe+0000000000F8537C, 00007FF6389A537C)
  00007FF77B1D467D (GTA5.exe+000000000164467D, 00007FF63906467D)
  00007FF77B1D467D (GTA5.exe+000000000164467D, 00007FF63906467D)
  00007FF77B1D467D (GTA5.exe+000000000164467D, 00007FF63906467D)
  00007FF77B1D3EB3 (GTA5.exe+0000000001643EB3, 00007FF639063EB3)
  00007FF779BB8340 (GTA5.exe+0000000000028340, 00007FF637A48340)
  00007FF779BB1A2B (GTA5.exe+0000000000021A2B, 00007FF637A41A2B)
  00007FF77B1D3ABC (GTA5.exe+0000000001643ABC, 00007FF639063ABC)
  00007FF779B91494 (GTA5.exe+0000000000001494, 00007FF637A21494)
  00007FF77AEA60CB (GTA5.exe+00000000013160CB, 00007FF638D360CB)
  00007FF77B3CA590 (GTA5.exe+000000000183A590, 00007FF63925A590)
  00007FFB1649257D (KERNEL32.DLL+000000000001257D): BaseThreadInitThunk
  00007FFB1768AF28 (ntdll.dll+000000000005AF28): RtlUserThreadStart
  00007FFB1768AF28 (ntdll.dll+000000000005AF28): RtlUserThreadStart
[26.06.2024 14:08:47] ---- ERROR INFORMATION ENDS ----

**Comment by Sainan** [comment]
Not a Stand issue

**Comment by Lechom** [comment]
> Not a Stand issue

so just the game being shit?
