### ISSUE TITLE
Increased Sticky Limit not working

### ISSUE THREAD

**Issue by 41Baloo** [calamity-inc/Stand-Feedback#98]
- Increasing the stickybomb limit via `Self>Weapons>Increased Sticky Limit` doesn't seem to do anything while online

- Enable `Increased Sticky Limit`
- go online
- throw more than 5 sticky bombs
- the first one will disappear

**Comment by alessandromrc** [comment]
> * Increasing the stickybomb limit via `Self>Weapons>Increased Sticky Limit` doesn't seem to do anything while online
> * Enable `Increased Sticky Limit`
> * go online
> * throw more than 5 sticky bombs
> * the first one will disappear

Cannot reproduce.
